import {programmes} from '@/lib/programmes';
import { notFound } from 'next/navigation';
import Site from '@/components/site';
import {services,countries,guides,slugify,origin} from '@/lib/content';
export async function generateMetadata({params}:{params:Promise<{locale:string,path?:string[]}>}){
 const {locale,path=[]}=await params; const programme=path[0]==='programmes'?programmes.find(p=>p.slug===path[1]):undefined; const s=services.find(x=>x.slug===path[1]);const c=countries.find(x=>slugify(x[0])===path[1]);const g=guides.find(x=>x.slug===path[1]);
 const names:Record<string,string>={programmes:'Explore programmes',about:'Our approach',services:'Our services',destinations:'Explore destinations',resources:'Your next chapter, informed',consultation:'Request a consultation',contact:'Contact',privacy:'Privacy',faqs:'Frequently asked questions'};
 const title=path.length?((locale==='ar'?programme?.ar:programme?.title)||s?.title||c?.[0]||g?.title||names[path[0]]||'Plan B Consultant'):'Your next chapter starts here';const route='/'+locale+(path.length?'/'+path.join('/'):'');
 const description=programme?(locale==='ar'?programme.introAr:programme.intro):(g?(locale==='ar'?g.introAr:g.intro):s?`Explore ${s.title.toLowerCase()} guidance from Plan B Consultant in Kuwait.`:c?`Explore immigration, work, study and investment options for ${c[0]} with Plan B Consultant.`:'Kuwait-based guidance for immigration, work, study, travel and business opportunities. Explore your next step with Plan B Consultant.');
 return {icons:{icon:'/images/plan-b-logo-'+locale+'.png'},title:title+' | Plan B Consultant',description,alternates:{canonical:origin+route,languages:{en:origin+route.replace(/^\/ar/,'/en'),ar:origin+route.replace(/^\/en/,'/ar')}},robots:{index:process.env.NEXT_PUBLIC_ALLOW_INDEXING==='true',follow:process.env.NEXT_PUBLIC_ALLOW_INDEXING==='true'}};
}
export default async function Page({params}:{params:Promise<{locale:string,path?:string[]}>}){const {locale,path=[]}=await params;if(!['en','ar'].includes(locale))notFound(); const valid=path.length===0||(path.length===1&&['programmes','about','services','destinations','resources','consultation','contact','privacy','faqs'].includes(path[0]))||(path.length===2&&((path[0]==='programmes'&&programmes.some(p=>p.slug===path[1]))||(path[0]==='services'&&services.some(x=>x.slug===path[1]))||(path[0]==='destinations'&&countries.some(x=>slugify(x[0])===path[1]))||(path[0]==='resources'&&guides.some(x=>x.slug===path[1]))));if(!valid)notFound();const route='/'+locale+(path.length?'/'+path.join('/'):''),programme=path[0]==='programmes'?programmes.find(p=>p.slug===path[1]):undefined;const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{ "@type":"ListItem",position:1,name:'Plan B Consultant',item:origin+'/'+locale},...path.map((part,index)=>({"@type":"ListItem",position:index+2,name:part.replace(/-/g,' '),item:origin+'/'+locale+'/'+path.slice(0,index+1).join('/')}))]};const service=programme?{"@context":"https://schema.org","@type":"Service",name:locale==='ar'?programme.ar:programme.title,description:locale==='ar'?programme.introAr:programme.intro,areaServed:'Kuwait',url:origin+route,provider:{"@type":"Organization",name:'Plan B Consultant'}}:null;return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb).replace(/</g,'\\u003c')}}/>{service&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(service).replace(/</g,'\\u003c')}}/>}<Site locale={locale as 'en'|'ar'} path={path}/></>;}
