'use client';
import {useState,useEffect,useId,type FormEvent} from 'react';
import {ArrowRight,ArrowLeft,CheckCircle2} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {programmes} from '@/lib/programmes';
import {countries,services,text,type Locale} from '@/lib/content';
const ages=['Under 21','21–32','33–39','40–45','46–55','56+'];
const budgets=['Not sure yet','Below USD 70,000','USD 70,000–149,999','USD 150,000–249,999','USD 250,000–349,999','USD 350,000–449,999','USD 450,000–549,999','USD 550,000–649,999','USD 650,000–749,999','USD 750,000–849,999','USD 850,000–1,049,999','USD 1,050,000 and above'];
const educationOptions=[['PhD','دكتوراه'],["Master’s degree",'ماجستير'],["Bachelor’s degree",'بكالوريوس'],['Diploma','دبلوم'],['High school','ثانوي'],['Other','غير ذلك']];
export default function Assessment({locale:l}:{locale:Locale}){
 const t=(a:string,b:string)=>text(l,a,b);const [step,setStep]=useState(0);const [status,setStatus]=useState('idle');const [error,setError]=useState('');const [reference,setReference]=useState('');
 const [v,setV]=useState({id:'',programme:'not-sure',service:'not-sure',destination:'Not sure yet',age:'',education:'',profession:'',nationality:'',residence:'Kuwait',budget:'Not sure yet',name:'',phone:'+965 ',email:'',message:'',website:'',consent:false,method:'whatsapp',offer:'not-sure'});
 const set=(k:string,value:string|boolean)=>setV(prev=>({...prev,[k]:value}));
 useEffect(()=>{const q=new URLSearchParams(location.search);const p=programmes.find(x=>x.slug===q.get('programme'));const s=services.find(x=>x.slug===q.get('service'));const d=countries.find(x=>x[0]===q.get('destination'));setV(prev=>({...prev,id:crypto.randomUUID(),programme:p?.slug||'not-sure',service:s?.slug||'not-sure',destination:p&&countries.some(c=>c[0]===p.country)?p.country:d?.[0]||'Not sure yet'}))},[]);
 const selected=programmes.find(p=>p.slug===v.programme);const investing=selected?.group==='business'||selected?.group==='citizenship';
 function picker(k:keyof typeof v,label:string,options:{value:string,label:string}[]){return <div className="form-label"><label htmlFor={'assessment-'+k}>{label}</label><Select value={String(v[k])} onValueChange={value=>{set(k,value);if(k==='programme'){const p=programmes.find(p=>p.slug===value);if(p&&countries.some(c=>c[0]===p.country))set('destination',p.country)}}}><SelectTrigger className="picker" id={'assessment-'+k} aria-label={label}><SelectValue placeholder={t('Select an option','اختر خياراً')}/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
 function input(k:keyof typeof v,label:string,required=true,type='text',max=100){return <label>{label}<input name={k} value={String(v[k])} onChange={e=>set(k,e.target.value)} required={required} type={type} maxLength={max} minLength={k==='name'?2:undefined} autoComplete={({name:'name',phone:'tel',email:'email'} as Record<string,string>)[k]||'off'} dir={type==='email'||type==='tel'?'ltr':undefined}/></label>}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(step===1&&(!v.age||!v.education)){setError(t('Select your age range and education.','اختر الفئة العمرية والمؤهل.'));return}if(step<2){setStep(step+1);return}if(status==='sending')return;setStatus('sending');try{const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...v,budget:investing?v.budget:'Not applicable',locale:l})});const data=await r.json() as {reference:string};if(!r.ok)throw new Error(r.status===429?t('Please wait before sending another request.','يرجى الانتظار قبل إرسال طلب آخر.'):t('We could not save your request. Please check your details and try again.','تعذر حفظ الطلب. راجع بياناتك وحاول مجدداً.'));setReference(data.reference);setStatus('success')}catch(err){setError(err instanceof Error?err.message:'Unable to connect');setStatus('error')}}
 if(status==='success')return <div className="form-success" role="status"><CheckCircle2 size={48}/><h2>{t('Your request is saved.','تم حفظ طلبك.')}</h2><p>{t('Keep your reference for follow-up. This is an enquiry, not an eligibility decision or a confirmed appointment.','احتفظ بالمرجع للمتابعة. هذا استفسار وليس قرار أهلية أو موعداً مؤكداً.')}</p><strong className="enquiry-reference">{reference}</strong><p>{t('Your details are available for review. Any appointment and next steps will need to be agreed separately.','بياناتك متاحة للمراجعة. يلزم الاتفاق بشكل منفصل على أي موعد والخطوات التالية.')}</p><a className="button" href={'/'+l}>{t('Back to home','العودة للرئيسية')}</a></div>;
 return <form className="enquiry-form assessment-form" onSubmit={submit}><div className="eyebrow">{t('FREE INITIAL ASSESSMENT','تقييم أولي مجاني')}</div><h3>{t('Start with your next step.','ابدأ بخطوتك القادمة.')}</h3><ol className="assessment-progress" aria-label={t('Assessment steps','خطوات التقييم')}>{[["Your plans","خططك"],["Profile · optional","ملفك · اختياري"],["Contact","التواصل"]].map((s,i)=><li key={s[0]} aria-current={step===i?'step':undefined} className={step>=i?'current':''}><span>{i+1}</span>{t(s[0],s[1])}</li>)}</ol><p className="step-description" aria-live="polite">{t('Step','الخطوة')} {step+1} / 3</p><div className="form-grid">
{step===0&&<>{picker('programme',t('Programme of interest','البرنامج المطلوب'),[{value:'not-sure',label:t('Help me choose','ساعدني على الاختيار')},...programmes.map(p=>({value:p.slug,label:t(p.title,p.ar)}))])}{picker('destination',t('Preferred destination','الوجهة المفضلة'),[{value:'Not sure yet',label:t('Still exploring','لا أزال أستكشف')},...countries.map(c=>({value:c[0],label:t(c[0],c[1])}))])}{investing&&<>{picker('budget',t('Indicative investment budget · USD','ميزانية الاستثمار التقريبية · دولار أمريكي'),budgets.map((b,i)=>({value:b,label:i===0?t(b,'لم أحدد بعد'):b})))}<p className="full small-note">{t('This is a planning range, not a quoted programme price or an eligibility threshold.','هذا نطاق للتخطيط وليس سعراً للبرنامج أو حداً للأهلية.')}</p></>}{selected?.group==='work'&&picker('offer',t('Do you have a job offer?','هل لديك عرض عمل؟'),[{value:'yes',label:t('Yes','نعم')},{value:'no',label:t('No','لا')},{value:'not-sure',label:t('I need guidance','أحتاج إرشاداً')}])}</>}
{step===1&&<><p className="full small-note">{t('Share your background now, or skip this step and discuss it during your consultation.','شارك خلفيتك الآن، أو تجاوز هذه الخطوة وناقشها أثناء الاستشارة.')}</p>{picker('age',t('Age range','الفئة العمرية'),ages.map((a,i)=>({value:a,label:i===0?t(a,'أقل من 21'):a})))}{picker('education',t('Highest education','أعلى مؤهل تعليمي'),educationOptions.map(e=>({value:e[0],label:t(e[0],e[1])})))}{input('profession',t('Current job designation','المسمى الوظيفي الحالي'))}{input('nationality',t('Nationality','الجنسية'))}{input('residence',t('Current country of residence','دولة الإقامة الحالية'))}</>}
{step===2&&<>{input('name',t('Full name','الاسم الكامل'))}{input('phone',t('Phone / WhatsApp','الهاتف / واتساب'),true,'tel',25)}{input('email',t('Email address','البريد الإلكتروني'),true,'email',200)}{picker('method',t('Preferred contact method','وسيلة التواصل المفضلة'),[{value:'whatsapp',label:'WhatsApp'},{value:'phone',label:t('Phone','الهاتف')},{value:'email',label:t('Email','البريد الإلكتروني')}])}<label className="full">{t('Additional information · optional','معلومات إضافية · اختياري')}<textarea value={v.message} onChange={e=>set('message',e.target.value)} rows={4} maxLength={2000}/></label><label className="consent full"><input required type="checkbox" checked={v.consent} onChange={e=>set('consent',e.target.checked)}/><span>{t('I agree to my details being stored and used to respond to this request.','أوافق على حفظ بياناتي واستخدامها للرد على هذا الطلب.')} <a href={'/'+l+'/privacy'}>{t('Privacy notice','إشعار الخصوصية')}</a></span></label></>}
</div><label className="honey" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={v.website} onChange={e=>set('website',e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}{step===1&&<button type="button" className="skip-profile" onClick={()=>{setV(prev=>({...prev,age:'',education:'',profession:'',nationality:'',residence:''}));setError('');setStep(2)}}>{t('Skip profile for now','تجاوز الملف الآن')}<ArrowRight size={16}/></button>}<div className="assessment-buttons">{step>0&&<button className="button outline" type="button" disabled={status==='sending'} onClick={()=>{setStep(step-1);setError('')}}><ArrowLeft size={16}/>{t('Back','رجوع')}</button>}<button className="button" type="submit" disabled={status==='sending'||!v.id}>{status==='sending'?t('Saving…','جارٍ الحفظ…'):step<2?t('Continue','متابعة'):t('Request free assessment','اطلب تقييماً مجانياً')}<ArrowRight size={16}/></button></div><p className="small-note">{t('No obligation. Do not include passport numbers, bank details or medical records.','دون التزام. لا تدرج أرقام جوازات أو بيانات مصرفية أو سجلات طبية.')}</p></form>
}

export function QuickAssessment({locale:l}:{locale:Locale}){
 const t=(a:string,b:string)=>text(l,a,b);const uid=useId();const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');const [error,setError]=useState('');const [reference,setReference]=useState('');
 const [v,setV]=useState({id:'',name:'',email:'',phone:'+965 ',age:'',education:'',profession:'',programme:'not-sure',consent:false,website:''});
 useEffect(()=>setV(prev=>({...prev,id:crypto.randomUUID()})),[]);
 const set=(key:keyof typeof v,value:string|boolean)=>setV(prev=>({...prev,[key]:value}));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(status==='sending')return;setError('');setStatus('sending');const programme=programmes.find(p=>p.slug===v.programme);try{const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...v,service:'not-sure',destination:programme?.country&&programme.country!=='Multiple destinations'?programme.country:'Not sure yet',offer:'not-sure',method:'whatsapp',message:'',nationality:'',residence:'',budget:'Not applicable',locale:l})});const data=await r.json() as {reference?:string,error?:string};if(!r.ok)throw new Error(r.status===503?t('Online enquiries are not configured yet. Please use the contact details shown above.','خدمة الاستفسارات الإلكترونية غير مهيأة بعد. استخدم بيانات التواصل أعلاه.'):data.error||t('We could not save your request. Check the fields and try again.','تعذر حفظ طلبك. راجع الحقول وحاول مجدداً.'));setReference(data.reference||'');setStatus('success')}catch(err){setStatus('error');setError(err instanceof Error?err.message:t('Unable to connect. Try again.','تعذر الاتصال. حاول مجدداً.'))}}
 if(status==='success')return <div className="quick-assessment quick-success" role="status"><CheckCircle2 size={38}/><h2>{t('Request received','تم استلام الطلب')}</h2><p>{t('Keep this reference for follow-up. This is not an eligibility decision or confirmed appointment.','احتفظ بهذا الرقم للمتابعة. هذا ليس قرار أهلية أو موعداً مؤكداً.')}</p><strong>{reference}</strong></div>;
 const fieldId=(name:string)=>`${uid}-${name}`;
 return <form className="quick-assessment" onSubmit={submit} aria-label={t('Free initial assessment','تقييم أولي مجاني')}>
  <div className="quick-heading"><span>{t('FREE ASSESSMENT','تقييم مجاني')}</span><h2>{t('Tell us where you want to go.','أخبرنا إلى أين تريد أن تصل.')}</h2></div>
  <label htmlFor={fieldId('name')}>{t('Full name','الاسم الكامل')}<input id={fieldId('name')} value={v.name} onChange={e=>set('name',e.target.value)} autoComplete="name" minLength={2} maxLength={100} required/></label>
  <label htmlFor={fieldId('email')}>{t('Email address','البريد الإلكتروني')}<input id={fieldId('email')} value={v.email} onChange={e=>set('email',e.target.value)} type="email" autoComplete="email" dir="ltr" maxLength={200} required/></label>
  <label htmlFor={fieldId('phone')}>{t('Contact / WhatsApp','رقم الاتصال / واتساب')}<input id={fieldId('phone')} value={v.phone} onChange={e=>set('phone',e.target.value)} type="tel" autoComplete="tel" dir="ltr" maxLength={25} required/></label>
  <label htmlFor={fieldId('age')}>{t('Age range','الفئة العمرية')}<select id={fieldId('age')} value={v.age} onChange={e=>set('age',e.target.value)} required><option value="">{t('Choose','اختر')}</option>{ages.map((a,i)=><option key={a} value={a}>{i===0?t(a,'أقل من 21'):a}</option>)}</select></label>
  <label htmlFor={fieldId('education')}>{t('Education','المؤهل التعليمي')}<select id={fieldId('education')} value={v.education} onChange={e=>set('education',e.target.value)} required><option value="">{t('Choose','اختر')}</option>{educationOptions.map(e=><option key={e[0]} value={e[0]}>{t(e[0],e[1])}</option>)}</select></label>
  <label htmlFor={fieldId('profession')}>{t('Profession / current role','المهنة / الوظيفة الحالية')}<input id={fieldId('profession')} value={v.profession} onChange={e=>set('profession',e.target.value)} maxLength={100} required/></label>
  <label htmlFor={fieldId('programme')}>{t('Programme','البرنامج')}<select id={fieldId('programme')} value={v.programme} onChange={e=>set('programme',e.target.value)} required><option value="not-sure">{t('Help me choose','ساعدني على الاختيار')}</option>{programmes.map(p=><option key={p.slug} value={p.slug}>{t(p.title,p.ar)}</option>)}</select></label>
  <label className="quick-consent"><input type="checkbox" checked={v.consent} onChange={e=>set('consent',e.target.checked)} required/><span>{t('I agree to the use of my details to respond to this enquiry.','أوافق على استخدام بياناتي للرد على هذا الاستفسار.')} <a href={'/'+l+'/privacy'}>{t('Privacy notice','إشعار الخصوصية')}</a></span></label>
  <label className="honey" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={v.website} onChange={e=>set('website',e.target.value)}/></label>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <button className="button" type="submit" disabled={status==='sending'||!v.id}>{status==='sending'?t('Sending…','جارٍ الإرسال…'):t('Send free assessment','أرسل التقييم المجاني')}<ArrowRight size={16}/></button>
  <p className="quick-note">{t('No obligation. Do not include passport, banking or medical details.','دون التزام. لا ترسل بيانات جواز السفر أو البيانات المصرفية أو الطبية.')}</p>
 </form>
}
