'use client';
import {emitConversion} from '@/lib/conversion-events';
import {useState,useEffect,useId,type FormEvent} from 'react';
import {ArrowRight,ArrowLeft,CheckCircle2} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {programmes} from '@/lib/programmes';
import {countries,services,text,type Locale} from '@/lib/content';
const ages=['21–32','33–39','40–45','46–55','56+'];
const budgets=['Not sure yet','Below USD 70,000','USD 70,000–149,999','USD 150,000–249,999','USD 250,000–349,999','USD 350,000–449,999','USD 450,000–549,999','USD 550,000–649,999','USD 650,000–749,999','USD 750,000–849,999','USD 850,000–1,049,999','USD 1,050,000 and above'];
const educationOptions=[['PhD','دكتوراه'],["Master’s degree",'ماجستير'],["Bachelor’s degree",'بكالوريوس'],['Diploma','دبلوم'],['High school','ثانوي'],['Other','غير ذلك']];
export default function Assessment({locale:l,initialProgramme}:{locale:Locale;initialProgramme?:string}){
 const t=(a:string,b:string)=>text(l,a,b);const [step,setStep]=useState(0);const [status,setStatus]=useState('idle');const [error,setError]=useState('');const [reference,setReference]=useState('');
 const initialProgram=programmes.find(program=>program.slug===initialProgramme);
 const [v,setV]=useState({id:'',programme:initialProgram?.slug||'not-sure',service:'not-sure',destination:initialProgram?.country||'Not sure yet',age:'',education:'',profession:'',nationality:'',residence:'Kuwait',budget:'Not sure yet',name:'',phone:'+965 ',email:'',message:'',website:'',consent:false,method:'whatsapp',offer:'not-sure'});
 const set=(k:string,value:string|boolean)=>setV(prev=>({...prev,[k]:value}));
 useEffect(()=>{const q=new URLSearchParams(location.search);const p=programmes.find(x=>x.slug===(q.get('programme')||initialProgramme));const s=services.find(x=>x.slug===q.get('service'));const d=countries.find(x=>x[0]===q.get('destination'));setV(prev=>({...prev,id:crypto.randomUUID(),programme:p?.slug||'not-sure',service:s?.slug||'not-sure',destination:p&&countries.some(c=>c[0]===p.country)?p.country:d?.[0]||'Not sure yet'}))},[initialProgramme]);
 const selected=programmes.find(p=>p.slug===v.programme);const investing=selected?.group==='business'||selected?.group==='citizenship';
 function picker(k:keyof typeof v,label:string,options:{value:string,label:string}[]){const value=String(v[k]);return <div className="form-label"><label htmlFor={'assessment-'+k}>{label}</label><Select value={value} onValueChange={next=>{set(k,next);if(k==='programme'){const p=programmes.find(p=>p.slug===next);if(p&&countries.some(c=>c[0]===p.country))set('destination',p.country)}}}><SelectTrigger className="picker" id={'assessment-'+k} aria-label={label}><SelectValue placeholder={t('Select an option','اختر خياراً')}>{options.find(option=>option.value===value)?.label}</SelectValue></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
 function input(k:keyof typeof v,label:string,required=true,type='text',max=100){return <label>{label}<input name={k} value={String(v[k])} onChange={e=>set(k,e.target.value)} required={required} type={type} maxLength={max} minLength={k==='name'?2:undefined} autoComplete={({name:'name',phone:'tel',email:'email'} as Record<string,string>)[k]||'off'} dir={type==='email'||type==='tel'?'ltr':undefined}/></label>}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(step===1&&(!v.age||!v.education)){setError(t('Select your age range and education.','اختر الفئة العمرية والمؤهل.'));return}if(step<2){emitConversion('assessment_step_completed',{locale:l,step:step+1});setStep(step+1);return}if(status==='sending')return;setStatus('sending');try{const r=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...v,budget:investing?v.budget:'Not applicable',locale:l})});const data=await r.json() as {reference:string};if(!r.ok)throw new Error(r.status===429?t('Please wait before sending another request.','يرجى الانتظار قبل إرسال طلب آخر.'):t('We could not save your request. Please check your details and try again.','تعذر حفظ الطلب. راجع بياناتك وحاول مجدداً.'));setReference(data.reference);emitConversion('assessment_step_completed',{locale:l,step:3});emitConversion('assessment_submission_success',{locale:l});setStatus('success')}catch(err){setError(err instanceof Error?err.message:'Unable to connect');setStatus('error')}}
 if(status==='success')return <div className="form-success" role="status"><CheckCircle2 size={48}/><h2>{t('Your request is saved.','تم حفظ طلبك.')}</h2><p>{t('Keep your reference for follow-up. This is an enquiry, not an eligibility decision or a confirmed appointment.','احتفظ بالمرجع للمتابعة. هذا استفسار وليس قرار أهلية أو موعداً مؤكداً.')}</p><strong className="enquiry-reference">{reference}</strong><p>{t('Your details are available for review. Any appointment and next steps will need to be agreed separately.','بياناتك متاحة للمراجعة. يلزم الاتفاق بشكل منفصل على أي موعد والخطوات التالية.')}</p><a className="button" href={'/'+l}>{t('Back to home','العودة للرئيسية')}</a></div>;
 return <form className="enquiry-form assessment-form" data-selected-programme={v.programme} onSubmit={submit}><div className="eyebrow">{t('FREE INITIAL ASSESSMENT','تقييم أولي مجاني')}</div><h3>{t('Start with your next step.','ابدأ بخطوتك القادمة.')}</h3><ol className="assessment-progress" aria-label={t('Assessment steps','خطوات التقييم')}>{[["Your plans","خططك"],["Profile · optional","ملفك · اختياري"],["Contact","التواصل"]].map((s,i)=><li key={s[0]} aria-current={step===i?'step':undefined} className={step>=i?'current':''}><span>{i+1}</span>{t(s[0],s[1])}</li>)}</ol><p className="step-description" aria-live="polite">{t('Step','الخطوة')} {step+1} / 3</p><div className="form-grid">
{step===0&&<>{picker('programme',t('Programme of interest','البرنامج المطلوب'),[{value:'not-sure',label:t('Help me choose','ساعدني على الاختيار')},...programmes.map(p=>({value:p.slug,label:t(p.title,p.ar)}))])}{picker('destination',t('Preferred destination','الوجهة المفضلة'),[{value:'Not sure yet',label:t('Still exploring','لا أزال أستكشف')},...countries.map(c=>({value:c[0],label:t(c[0],c[1])}))])}{investing&&<>{picker('budget',t('Indicative investment budget · USD','ميزانية الاستثمار التقريبية · دولار أمريكي'),budgets.map((b,i)=>({value:b,label:i===0?t(b,'لم أحدد بعد'):b})))}<p className="full small-note">{t('This is a planning range, not a quoted programme price or an eligibility threshold.','هذا نطاق للتخطيط وليس سعراً للبرنامج أو حداً للأهلية.')}</p></>}{selected?.group==='work'&&picker('offer',t('Do you have a job offer?','هل لديك عرض عمل؟'),[{value:'yes',label:t('Yes','نعم')},{value:'no',label:t('No','لا')},{value:'not-sure',label:t('I need guidance','أحتاج إرشاداً')}])}</>}
{step===1&&<><p className="full small-note">{t('Share your background now, or skip this step and discuss it during your consultation.','شارك خلفيتك الآن، أو تجاوز هذه الخطوة وناقشها أثناء الاستشارة.')}</p>{picker('age',t('Age range','الفئة العمرية'),ages.map(a=>({value:a,label:a})))}{picker('education',t('Highest education','أعلى مؤهل تعليمي'),educationOptions.map(e=>({value:e[0],label:t(e[0],e[1])})))}{input('profession',t('Current job designation','المسمى الوظيفي الحالي'))}{input('nationality',t('Nationality','الجنسية'))}{input('residence',t('Current country of residence','دولة الإقامة الحالية'))}</>}
{step===2&&<>{input('name',t('Full name','الاسم الكامل'))}{input('phone',t('Phone / WhatsApp','الهاتف / واتساب'),true,'tel',25)}{input('email',t('Email address','البريد الإلكتروني'),true,'email',200)}{picker('method',t('Preferred contact method','وسيلة التواصل المفضلة'),[{value:'whatsapp',label:'WhatsApp'},{value:'phone',label:t('Phone','الهاتف')},{value:'email',label:t('Email','البريد الإلكتروني')}])}<label className="full">{t('Additional information · optional','معلومات إضافية · اختياري')}<textarea value={v.message} onChange={e=>set('message',e.target.value)} rows={4} maxLength={2000}/></label><label className="consent full"><input required type="checkbox" checked={v.consent} onChange={e=>set('consent',e.target.checked)}/><span>{t('I agree to my details being stored and used to respond to this request.','أوافق على حفظ بياناتي واستخدامها للرد على هذا الطلب.')} <a href={'/'+l+'/privacy'}>{t('Privacy notice','إشعار الخصوصية')}</a></span></label></>}
</div><label className="honey" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={v.website} onChange={e=>set('website',e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}{step===1&&<button type="button" className="skip-profile" onClick={()=>{setV(prev=>({...prev,age:'',education:'',profession:'',nationality:'',residence:''}));setError('');emitConversion('assessment_step_completed',{locale:l,step:2});setStep(2)}}>{t('Skip profile for now','تجاوز الملف الآن')}<ArrowRight size={16}/></button>}<div className="assessment-buttons">{step>0&&<button className="button outline" type="button" disabled={status==='sending'} onClick={()=>{setStep(step-1);setError('')}}><ArrowLeft size={16}/>{t('Back','رجوع')}</button>}<button className="button" type="submit" disabled={status==='sending'||!v.id}>{status==='sending'?t('Saving…','جارٍ الحفظ…'):step<2?t('Continue','متابعة'):t('Request free assessment','اطلب تقييماً مجانياً')}<ArrowRight size={16}/></button></div><p className="small-note">{t('No obligation. Do not include passport numbers, bank details or medical records.','دون التزام. لا تدرج أرقام جوازات أو بيانات مصرفية أو سجلات طبية.')}</p></form>
}

export function GeneralEnquiry({locale:l}:{locale:Locale}){
 const t=(a:string,b:string)=>text(l,a,b);const uid=useId();const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');const [error,setError]=useState('');const [reference,setReference]=useState('');
 const [v,setV]=useState({id:'',name:'',email:'',phone:'+965 ',service:'not-sure',message:'',consent:false,website:''});
 useEffect(()=>setV(prev=>({...prev,id:crypto.randomUUID()})),[]);
 const set=(key:keyof typeof v,value:string|boolean)=>setV(prev=>({...prev,[key]:value}));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(status==='sending')return;setStatus('sending');setError('');try{const response=await fetch('/api/enquiries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...v,programme:'not-sure',destination:'Not sure yet',age:'',education:'',profession:'',nationality:'',residence:'Kuwait',budget:'Not applicable',offer:'not-sure',method:'email',locale:l})});const data=await response.json() as {reference?:string;error?:string};if(!response.ok)throw new Error(response.status===503?t('Online enquiries are not configured yet. Please use the available contact actions.','خدمة الاستفسارات الإلكترونية غير مهيأة بعد. استخدم وسائل التواصل المتاحة.'):data.error||t('We could not save your enquiry. Review the fields and try again.','تعذر حفظ استفسارك. راجع الحقول وحاول مجدداً.'));setReference(data.reference||'');emitConversion('contact_submission_success',{locale:l});setStatus('success')}catch(err){setStatus('error');setError(err instanceof Error?err.message:t('Unable to connect. Please try again.','تعذر الاتصال. يرجى المحاولة مجدداً.'))}}
 if(status==='success')return <div className="form-success general-enquiry-success" role="status"><CheckCircle2 size={44}/><h2>{t('Your enquiry is saved.','تم حفظ استفسارك.')}</h2><p>{t('Keep this reference for follow-up. Submission does not confirm an appointment or an outcome.','احتفظ بهذا الرقم للمتابعة. لا يعني الإرسال تأكيد موعد أو نتيجة.')}</p><strong className="enquiry-reference">{reference}</strong></div>;
 const id=(name:string)=>`${uid}-${name}`;
 return <form className="enquiry-form general-enquiry-form" onSubmit={submit} aria-label={t('General enquiry','استفسار عام')}>
  <div className="eyebrow">{t('GENERAL ENQUIRY','استفسار عام')}</div><h3>{t('Tell us how we can help.','أخبرنا كيف يمكننا مساعدتك.')}</h3>
  <div className="form-grid">
   <label htmlFor={id('name')}>{t('Name','الاسم')}<input id={id('name')} value={v.name} onChange={e=>set('name',e.target.value)} autoComplete="name" minLength={2} maxLength={100} required/></label>
   <label htmlFor={id('email')}>{t('Email','البريد الإلكتروني')}<input id={id('email')} value={v.email} onChange={e=>set('email',e.target.value)} type="email" autoComplete="email" dir="ltr" maxLength={200} required/></label>
   <label htmlFor={id('phone')}>{t('Contact Number','رقم التواصل')}<input id={id('phone')} value={v.phone} onChange={e=>set('phone',e.target.value)} type="tel" autoComplete="tel" dir="ltr" maxLength={25} required/></label>
   <label htmlFor={id('service')}>{t('Service of Interest','الخدمة المطلوبة')}<select id={id('service')} value={v.service} onChange={e=>set('service',e.target.value)} required><option value="not-sure">{t('Help me choose','ساعدني على الاختيار')}</option>{services.map(service=><option key={service.slug} value={service.slug}>{t(service.title,service.ar)}</option>)}</select></label>
   <label className="full" htmlFor={id('message')}>{t('Message','الرسالة')}<textarea id={id('message')} value={v.message} onChange={e=>set('message',e.target.value)} rows={5} minLength={5} maxLength={2000} required/></label>
   <label className="consent full"><input required type="checkbox" checked={v.consent} onChange={e=>set('consent',e.target.checked)}/><span>{t('I agree to my details being stored and used to respond to this enquiry.','أوافق على حفظ بياناتي واستخدامها للرد على هذا الاستفسار.')} <a href={'/'+l+'/privacy'}>{t('Privacy notice','إشعار الخصوصية')}</a></span></label>
  </div>
  <label className="honey" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={v.website} onChange={e=>set('website',e.target.value)}/></label>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <button className="button" type="submit" disabled={status==='sending'||!v.id}>{status==='sending'?t('Sending…','جارٍ الإرسال…'):t('Send Enquiry','إرسال الاستفسار')}<ArrowRight size={16}/></button>
  <p className="small-note">{t('Do not include passport numbers, banking details or medical records.','لا ترسل أرقام جوازات السفر أو البيانات المصرفية أو السجلات الطبية.')}</p>
 </form>;
}
