'use client';
import {useState} from 'react';
import {ArrowUpRight,Compass,Search,MapPin} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {programmes} from '@/lib/programmes';
import {countries,slugify,text,type Locale} from '@/lib/content';
function Picker({value,onChange,label,options,id}:{value:string,onChange:(s:string)=>void,label:string,options:{value:string,label:string}[],id?:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="picker" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent position="popper">{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function PathFinder({locale:l}:{locale:Locale}){const t=(a:string,b:string)=>text(l,a,b);const [goal,setGoal]=useState('canada-express-entry');const [dest,setDest]=useState('Not sure yet');return <div className="path-finder"><div className="path-title"><Compass size={28} strokeWidth={1.4}/><div><span>{t('YOUR NEXT CHAPTER','فصلك القادم')}</span><h2>{t('Find your starting point.','جد نقطة البداية.')}</h2></div></div><div className="path-choice"><label htmlFor="goal">{t('I would like to','أرغب في')}</label><Picker id="goal" label={t('Choose a goal','اختر هدفاً')} value={goal} onChange={setGoal} options={programmes.map(s=>({value:s.slug,label:t(s.title,s.ar)}))}/></div><div className="path-choice"><label htmlFor="destination">{t('My destination','وجهتي')}</label><Picker id="destination" label={t('Choose destination','اختر الوجهة')} value={dest} onChange={setDest} options={[{value:'Not sure yet',label:t('Still exploring','لا أزال أستكشف')},...countries.filter(c=>['Canada','Australia','Germany','Sweden','Portugal','United States'].includes(c[0])).map(c=>({value:c[0],label:t(c[0],c[1])}))]}/></div><a className="button" href={'/'+l+'/consultation?programme='+goal+'&destination='+encodeURIComponent(dest)}>{t('Let’s explore','لنستكشف')}<ArrowUpRight size={18}/></a></div>}
export default function DestinationDirectory({locale:l}:{locale:Locale}){const t=(a:string,b:string)=>text(l,a,b);const [q,setQ]=useState('');const [region,setRegion]=useState('All');const filtered=countries.filter(c=>(region==='All'||c[2]===region)&&c.slice(0,2).join(' ').toLowerCase().includes(q.trim().toLowerCase()));return <section className="wrap section tight"><div className="directory-controls"><label className="search-field"><Search size={21}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t('Find your destination…','ابحث عن وجهتك…')} aria-label={t('Search destinations','ابحث عن الوجهات')}/></label><Picker value={region} onChange={setRegion} label={t('Region','المنطقة')} options={['All','Europe','Asia','Americas','Oceania','Africa'].map((r,i)=>({value:r,label:t(r,['كل المناطق','أوروبا','آسيا','الأمريكتان','أوقيانوسيا','أفريقيا'][i])}))}/></div><p className="results-count" aria-live="polite">{filtered.length} {t('destinations to explore','وجهة للاستكشاف')}</p><div className="country-grid">{filtered.map(c=><a key={c[0]} href={'/'+l+'/destinations/'+slugify(c[0])}><MapPin size={20} strokeWidth={1.4}/><div><h3>{t(c[0],c[1])}</h3><span>{t('Explore your options','استكشف خياراتك')}</span></div><ArrowUpRight size={18}/></a>)}</div>{!filtered.length&&<div className="empty-state"><h2>{t('No destinations found','لم نعثر على وجهات')}</h2><p>{t('Try another spelling or choose all regions.','جرّب كتابة أخرى أو اختر جميع المناطق.')}</p><button className="button outline" onClick={()=>{setQ('');setRegion('All')}}>{t('Clear filters','مسح الفلاتر')}</button></div>}</section>}

