export type Locale = 'en' | 'ar';
export const text = (locale: Locale, en: string, ar: string) => locale === 'ar' ? ar : en;
export const origin = (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/,'');
export const business = { phone: process.env.NEXT_PUBLIC_PHONE || '', whatsapp: process.env.NEXT_PUBLIC_WHATSAPP || '', email: process.env.NEXT_PUBLIC_EMAIL || '', address: process.env.NEXT_PUBLIC_ADDRESS || '', hours: process.env.NEXT_PUBLIC_HOURS || '' };
export const services = [
 {slug:'skilled-immigration',title:'Skilled immigration',ar:'هجرة الكفاءات',short:'A new country. A new beginning.',shortAr:'بلد جديد. بداية جديدة.',description:'Explore migration pathways around your qualifications, experience and long-term ambitions.',descriptionAr:'استكشف مسارات الهجرة المناسبة لمؤهلاتك وخبراتك وطموحاتك.',icon:'globe',items:['Destination and pathway discussion','Profile and qualification review','Application preparation guidance','Family relocation considerations'],itemsAr:['مناقشة الوجهة والمسار','مراجعة المؤهلات والخبرات','إرشادات إعداد الطلب','اعتبارات انتقال الأسرة'],countries:['Canada','Australia','United Kingdom']},
 {slug:'work-visas',title:'Work visas & permits',ar:'تأشيرات وتصاريح العمل',short:'Take your career further.',shortAr:'خطوة جديدة في مسيرتك المهنية.',description:'Understand the preparation and application steps for your next professional move abroad.',descriptionAr:'تعرّف على خطوات التحضير والتقديم لخطوتك المهنية القادمة في الخارج.',icon:'briefcase',items:['Review of your work plans and offer status','Destination-specific document guidance','Application preparation support','Guidance on next steps'],itemsAr:['مراجعة خطط العمل وحالة العرض الوظيفي','إرشادات المستندات حسب الوجهة','المساعدة في إعداد الطلب','توضيح الخطوات التالية'],countries:['Canada','Australia','United Kingdom','Poland','Czech Republic','Singapore','Malaysia']},
 {slug:'visit-visas',title:'Visit visas',ar:'تأشيرات الزيارة',short:'Make room for new experiences.',shortAr:'افتح المجال لتجارب جديدة.',description:'From a long-awaited holiday to a family reunion, prepare for your journey with greater clarity.',descriptionAr:'من إجازة طال انتظارها إلى لقاء العائلة، استعد لرحلتك برؤية أوضح.',icon:'plane',items:['Travel-purpose discussion','Document checklist guidance','Application preparation','Appointment and interview preparation where applicable'],itemsAr:['مناقشة غرض السفر','إرشادات قائمة المستندات','إعداد الطلب','الاستعداد للمواعيد والمقابلات عند الحاجة'],countries:['Canada','Australia','United Kingdom','United States','New Zealand','Schengen']},
 {slug:'study-abroad',title:'Study abroad',ar:'الدراسة في الخارج',short:'A world of learning awaits.',shortAr:'عالم من فرص التعلم ينتظرك.',description:'Connect your education goals with course, admission and student-visa guidance.',descriptionAr:'اربط أهدافك التعليمية بإرشادات البرامج والقبول وتأشيرات الدراسة.',icon:'graduation',items:['Course and university exploration','Admission preparation','Student-visa document guidance','Interview and pre-departure preparation'],itemsAr:['استكشاف البرامج والجامعات','الاستعداد للقبول','إرشادات مستندات تأشيرة الطالب','الاستعداد للمقابلة وما قبل السفر'],countries:['Canada','Australia','United Kingdom','United States','New Zealand']},
 {slug:'global-job-search',title:'Global job search',ar:'البحث عن عمل عالمي',short:'Put your potential on the map.',shortAr:'امنح إمكاناتك فرصة عالمية.',description:'Present your experience confidently with focused support for your international job search.',descriptionAr:'قدّم خبراتك بثقة مع دعم مركّز للبحث عن عمل دولي.',icon:'search',items:['Career planning and professional CVs','Cover letters and LinkedIn profiles','Employer and recruitment-agency outreach','Job-application assistance'],itemsAr:['التخطيط المهني والسيرة الذاتية','خطابات التقديم وملفات لينكدإن','التواصل مع أصحاب العمل ووكالات التوظيف','دعم طلبات التوظيف'],countries:['Canada','Australia','United Kingdom','Singapore','Malaysia']},
 {slug:'business-immigration',title:'Business & investment',ar:'الأعمال والاستثمار',short:'Think beyond borders.',shortAr:'فكّر خارج الحدود.',description:'Explore international business and residency possibilities around your entrepreneurial goals.',descriptionAr:'استكشف فرص الأعمال والإقامة الدولية وفق أهدافك الريادية.',icon:'building',items:['Discussion of business and investment goals','Exploration of relevant destinations','Preparation requirements overview','Coordination of agreed application support'],itemsAr:['مناقشة أهداف الأعمال والاستثمار','استكشاف الوجهات المناسبة','مراجعة متطلبات التحضير','تنسيق دعم الطلب المتفق عليه'],countries:[]},
 {slug:'family-visas',title:'Family & dependent visas',ar:'تأشيرات الأسرة والمعالين',short:'Plan your future, together.',shortAr:'خططوا لمستقبلكم معاً.',description:'Understand the steps involved in joining or accompanying family abroad.',descriptionAr:'تعرّف على خطوات الانضمام إلى عائلتك أو مرافقتها في الخارج.',icon:'users',items:['Family circumstances discussion','Relationship document preparation','Destination-specific checklist guidance','Support with application preparation'],itemsAr:['مناقشة ظروف الأسرة','إعداد مستندات صلة القرابة','إرشادات القائمة حسب الوجهة','دعم إعداد الطلب'],countries:['Canada','Australia','United Kingdom']},
 {slug:'permanent-residency',title:'Permanent residency support',ar:'دعم الإقامة الدائمة',short:'Build a longer-term future.',shortAr:'ابنِ مستقبلاً على المدى الطويل.',description:'Discuss residency applications, documentation and PR-card renewal support where applicable.',descriptionAr:'ناقش طلبات الإقامة والمستندات ودعم تجديد بطاقة الإقامة الدائمة عند انطباقها.',icon:'globe',items:['Review of current residency circumstances','Application document guidance','PR-card renewal preparation where applicable','Next-step planning'],itemsAr:['مراجعة وضع الإقامة الحالي','إرشادات مستندات الطلب','التحضير لتجديد بطاقة الإقامة عند انطباقه','تخطيط الخطوات التالية'],countries:['Canada','Australia']},
 {slug:'ielts-preparation',title:'IELTS preparation',ar:'الاستعداد لاختبار آيلتس',short:'Move forward with confidence.',shortAr:'تقدّم بثقة.',description:'Discuss language preparation around your education, career or migration plans.',descriptionAr:'ناقش الاستعداد اللغوي المرتبط بخطط الدراسة أو العمل أو الهجرة.',icon:'graduation',items:['Learning goals discussion','Listening and reading preparation','Writing and speaking preparation','Study planning and practice guidance'],itemsAr:['مناقشة أهداف التعلم','الاستعداد للاستماع والقراءة','الاستعداد للكتابة والمحادثة','تخطيط الدراسة وإرشادات التدريب'],countries:[]},
 {slug:'settlement-support',title:'Pre-departure & settlement',ar:'ما قبل السفر والاستقرار',short:'Prepare for life beyond arrival.',shortAr:'استعد للحياة بعد الوصول.',description:'Organise practical questions before departure and discuss the support available after arrival.',descriptionAr:'نظّم أسئلتك العملية قبل السفر وناقش الدعم المتاح بعد الوصول.',icon:'compass',items:['Pre-departure checklist','Arrival planning discussion','Housing and local-system information','Agreed post-arrival support'],itemsAr:['قائمة ما قبل السفر','مناقشة خطة الوصول','معلومات السكن والأنظمة المحلية','دعم ما بعد الوصول المتفق عليه'],countries:[]}
];
export const countries = [
['Canada','كندا','Americas'],['Australia','أستراليا','Oceania'],['United Kingdom','المملكة المتحدة','Europe'],['United States','الولايات المتحدة','Americas'],['New Zealand','نيوزيلندا','Oceania'],['Schengen','شنغن','Europe'],['Thailand','تايلاند','Asia'],['Japan','اليابان','Asia'],['Turkey','تركيا','Europe'],['China','الصين','Asia'],['South Korea','كوريا الجنوبية','Asia'],['Saudi Arabia','السعودية','Asia'],['Malaysia','ماليزيا','Asia'],['Singapore','سنغافورة','Asia'],['Ireland','أيرلندا','Europe'],['Cyprus','قبرص','Europe'],['Russia','روسيا','Europe'],['Italy','إيطاليا','Europe'],['France','فرنسا','Europe'],['Switzerland','سويسرا','Europe'],['Germany','ألمانيا','Europe'],['Greece','اليونان','Europe'],['Finland','فنلندا','Europe'],['Netherlands','هولندا','Europe'],['Spain','إسبانيا','Europe'],['Sweden','السويد','Europe'],['Austria','النمسا','Europe'],['Iceland','آيسلندا','Europe'],['Poland','بولندا','Europe'],['Czech Republic','التشيك','Europe'],['Lithuania','ليتوانيا','Europe'],['Latvia','لاتفيا','Europe'],['Estonia','إستونيا','Europe'],['Monaco','موناكو','Europe'],['San Marino','سان مارينو','Europe'],['Liechtenstein','ليختنشتاين','Europe'],['Luxembourg','لوكسمبورغ','Europe'],['Vatican City','الفاتيكان','Europe'],['Slovakia','سلوفاكيا','Europe'],['Bulgaria','بلغاريا','Europe'],['Slovenia','سلوفينيا','Europe'],['Hungary','المجر','Europe'],['Portugal','البرتغال','Europe'],['Norway','النرويج','Europe'],['Tanzania','تنزانيا','Africa'],['Brazil','البرازيل','Americas']];
export const slugify = (s:string) => s.toLowerCase().replaceAll(' ','-');
export const guides = [
{slug:'prepare-for-your-consultation',title:'Your first consultation: what to prepare',ar:'استشارتك الأولى: كيف تستعد',tag:'GETTING STARTED',tagAr:'البداية',intro:'A useful first conversation starts with a clear picture of your plans. You do not need to have every answer before you get in touch.',introAr:'تبدأ المحادثة المفيدة بصورة واضحة عن خططك. لا تحتاج إلى معرفة كل الإجابات قبل التواصل.',sections:[['Start with your goal','Are you exploring work, study, travel or a longer-term move? Write down your preferred destination, your ideal timing and the questions you want to discuss.'],['Bring a simple overview','Prepare a summary of your education, work experience and current country of residence. For study enquiries, include your preferred subject. For work enquiries, mention whether you have an offer.'],['Ask about scope and fees','Before agreeing to any service, ask what is included, what you must do yourself and which fees are paid to third parties. Keep a copy of the agreed terms.']],sectionsAr:[['ابدأ بهدفك','هل تفكر في العمل أو الدراسة أو السفر أو الانتقال؟ دوّن وجهتك المفضلة وتوقيتك وأسئلتك.'],['جهّز ملخصاً بسيطاً','حضّر ملخصاً لتعليمك وخبرتك ومكان إقامتك الحالي. اذكر تخصصك المطلوب للدراسة أو وجود عرض عمل.'],['اسأل عن النطاق والرسوم','اسأل عن الخدمات المشمولة ومسؤولياتك ورسوم الأطراف الأخرى قبل الاتفاق. احتفظ بنسخة من الشروط.']]},
{slug:'job-search-or-work-visa',title:'Job search or work visa: where to begin?',ar:'بحث عن عمل أم تأشيرة عمل؟',tag:'WORK ABROAD',tagAr:'العمل بالخارج',intro:'These services address different stages of an overseas career. Knowing your starting point makes the next conversation more useful.',introAr:'تغطي هذه الخدمات مراحل مختلفة من العمل بالخارج. تحديد نقطة البداية يجعل الاستشارة أكثر فائدة.',sections:[['If you are looking for a role','Career support can focus on presenting your experience, preparing your CV and planning applications. It does not guarantee employment.'],['If you already have an offer','Your questions may concern the employer, destination, documents and work-authorisation process. An offer alone does not establish visa eligibility.'],['Keep responsibilities clear','Ask which steps belong to you, the employer and the consultancy. Verify information about the employer and never assume a payment guarantees a job or visa.']],sectionsAr:[['إذا كنت تبحث عن وظيفة','قد يركز الدعم المهني على عرض خبراتك وإعداد سيرتك وتخطيط الطلبات. لا يضمن ذلك التوظيف.'],['إذا كان لديك عرض بالفعل','قد تتعلق أسئلتك بصاحب العمل والوجهة والمستندات وتصريح العمل. العرض وحده لا يثبت أهلية التأشيرة.'],['وضّح المسؤوليات','اسأل عن دورك ودور صاحب العمل والاستشاري. تحقّق من صاحب العمل ولا تفترض أن الدفع يضمن وظيفة أو تأشيرة.']]},
{slug:'organise-your-documents',title:'A calmer way to organise your documents',ar:'طريقة أبسط لتنظيم مستنداتك',tag:'PLANNING AHEAD',tagAr:'التخطيط مسبقاً',intro:'A tidy document folder helps you discuss your plans clearly and respond to requests without unnecessary confusion.',introAr:'يساعدك تنظيم مستنداتك على مناقشة خططك بوضوح والاستجابة للطلبات بسهولة.',sections:[['Keep a working list','Use the checklist for your selected application. General online lists are a starting point, not a substitute for current destination-specific requirements.'],['Check consistency','Review names, dates and contact details across your documents. Ask how to handle discrepancies before submitting anything.'],['Share carefully','Do not send passports, financial records or other sensitive documents through an initial enquiry form. Confirm the appropriate secure channel with your consultant.']],sectionsAr:[['استخدم قائمة واضحة','اعتمد قائمة طلبك المحدد. القوائم العامة لا تحل محل متطلبات الوجهة الحالية.'],['راجع الاتساق','راجع الأسماء والتواريخ وبيانات الاتصال. اسأل عن معالجة الاختلافات قبل التقديم.'],['شارك بحذر','لا ترسل جوازات السفر أو السجلات المالية عبر نموذج الاستفسار الأولي. اتفق على قناة آمنة مع مستشارك.']]}
];
export const faqs = [
['I’m not sure where to start. Can I still enquire?','Yes. Tell us what you hope to achieve, even if you have not chosen a destination. Your first conversation can help clarify the questions and options to explore.','لم أختر وجهتي بعد. هل يمكنني الاستفسار؟','نعم. أخبرنا بما تريد تحقيقه حتى لو لم تختر وجهة. يمكن للمحادثة الأولى توضيح الخيارات والأسئلة.'],
['What should I prepare for a consultation?','A brief summary of your goals, current country of residence, education and work experience is a useful starting point. Please do not submit sensitive documents through the initial enquiry form.','ماذا أحضّر للاستشارة؟','ابدأ بملخص لأهدافك وبلد إقامتك ومؤهلاتك وخبرتك. لا ترسل مستندات حساسة عبر نموذج الاستفسار الأولي.'],
['Is job-search support the same as a work visa?','No. Job-search support helps you prepare for and pursue opportunities. Work-visa support concerns the application process for permission to work. Tell us whether you already have a job offer.','هل دعم البحث عن عمل هو نفسه تأشيرة العمل؟','لا. يدعم البحث عن عمل استعدادك ومتابعتك للفرص. تتعلق تأشيرة العمل بإجراءات الإذن بالعمل. أخبرنا إذا كان لديك عرض وظيفي.'],
['Are visa approvals or jobs guaranteed?','No. Immigration authorities decide visa applications and employers decide hiring. Consultancy support does not guarantee either outcome.','هل الموافقة أو الوظيفة مضمونة؟','لا. تقرر الجهات المختصة طلبات التأشيرات ويقرر أصحاب العمل التوظيف. الدعم الاستشاري لا يضمن النتائج.'],
['How much will my application cost?','Costs depend on your destination, application and agreed services. Ask for a written breakdown that separates consultancy fees from government and other third-party charges before proceeding.','كم تبلغ تكلفة طلبي؟','تعتمد التكلفة على الوجهة والطلب والخدمات المتفق عليها. اطلب تفصيلاً مكتوباً يفصل أتعاب الاستشارة عن الرسوم الحكومية وغيرها.'],
['Can I include my family in my plans?','You can discuss family and dependent support during your consultation. Available options depend on the destination, application category and your circumstances.','هل يمكنني إدراج أسرتي في خططي؟','يمكنك مناقشة دعم الأسرة والمعالين. تعتمد الخيارات على الوجهة وفئة الطلب وظروفك.']
];
