export type Bilingual=[string,string];
export type ProgrammeDetail={
 overview:Bilingual[];
 pathways:{name:Bilingual;status:Bilingual;description:Bilingual}[];
 documents:Bilingual[];
 faqs:{question:Bilingual;answer:Bilingual}[];
};

export const programmeDetails:Record<string,ProgrammeDetail>={
 'canada-express-entry':{
  overview:[
   ['Express Entry is the federal online system used to manage skilled-worker applications under the Canadian Experience Class, Federal Skilled Worker Program and Federal Skilled Trades Program.','إكسبريس إنتري هو النظام الفيدرالي الإلكتروني لإدارة طلبات العمال المهرة ضمن فئة الخبرة الكندية وبرنامج العمال المهرة الفيدرالي وبرنامج الحرفيين المهرة الفيدرالي.'],
   ['Eligibility for one of those programs comes first. Eligible profiles enter the pool and are ranked using the Comprehensive Ranking System (CRS); an eligible profile is not itself an invitation.','تأتي أولاً أهلية المتقدم لأحد هذه البرامج. تدخل الملفات المؤهلة إلى المجموعة وتُرتب وفق نظام التصنيف الشامل (CRS)، ولا تعني أهلية الملف صدور دعوة بحد ذاتها.']
  ],
  pathways:[
   {name:['Federal Skilled Worker Program','برنامج العمال المهرة الفيدرالي'],status:['Permanent residence program','برنامج إقامة دائمة'],description:['For eligible skilled workers with qualifying experience. Its separate 100-point selection grid uses a 67-point threshold before pool ranking.','للعمال المهرة المؤهلين ذوي الخبرة المستوفية. يستخدم جدول اختيار منفصلاً من 100 نقطة بحد 67 نقطة قبل ترتيب الملف في المجموعة.']},
   {name:['Canadian Experience Class','فئة الخبرة الكندية'],status:['Permanent residence program','برنامج إقامة دائمة'],description:['For eligible applicants with qualifying skilled work experience in Canada. The 67-point FSW grid does not apply to this class.','للمتقدمين المؤهلين ذوي الخبرة العملية الماهرة المستوفية داخل كندا. لا ينطبق عليها جدول نقاط FSW البالغ 67 نقطة.']},
   {name:['Federal Skilled Trades Program','برنامج الحرفيين المهرة الفيدرالي'],status:['Permanent residence program','برنامج إقامة دائمة'],description:['For eligible workers in qualifying skilled trades who meet the program-specific work, language and job-offer or certification rules.','للعاملين المؤهلين في الحرف الماهرة المستوفية لمتطلبات الخبرة واللغة وعرض العمل أو شهادة التأهيل الخاصة بالبرنامج.']}
  ],
  documents:[
   ['Approved language-test results','نتائج اختبار لغة معتمد'],['Educational Credential Assessment for foreign education where required','تقييم المؤهل التعليمي للدراسة الأجنبية عند الحاجة'],['Detailed employer reference letters and work-history evidence','خطابات خبرة مفصلة وأدلة السجل المهني'],['Identity and civil-status records for included family members','مستندات الهوية والحالة المدنية لأفراد الأسرة المشمولين'],['Police certificates, medical examination and settlement-fund evidence when applicable','شهادات الشرطة والفحص الطبي وإثبات أموال الاستقرار عند انطباقها']
  ],
  faqs:[
   {question:['Is 67 the required CRS score?','هل 67 هي درجة CRS المطلوبة؟'],answer:['No. The 67/100 threshold belongs to the Federal Skilled Worker selection-factor grid. CRS is a separate ranking system used after an eligible profile enters the Express Entry pool.','لا. حد 67 من 100 يخص جدول عوامل اختيار العمال المهرة الفيدرالي. أما CRS فهو نظام ترتيب منفصل يُستخدم بعد دخول الملف المؤهل إلى مجموعة إكسبريس إنتري.']},
   {question:['Does a job offer still add CRS points?','هل يضيف عرض العمل نقاطاً إلى CRS؟'],answer:['IRCC removed CRS job-offer points in March 2025. A valid offer can still matter for eligibility under particular programs, so it must still be disclosed accurately.','أزالت IRCC نقاط عرض العمل من CRS في مارس 2025. ومع ذلك قد يظل العرض الصحيح مهماً لأهلية بعض البرامج، لذلك يجب الإفصاح عنه بدقة.']},
   {question:['How long do I have after an invitation?','كم لدي من الوقت بعد الدعوة؟'],answer:['The invitation specifies the filing deadline. IRCC currently generally gives 60 days, but the invitation and current official instructions control.','تحدد الدعوة مهلة التقديم. تمنح IRCC حالياً 60 يوماً عادةً، لكن الدعوة والتعليمات الرسمية السارية هي المرجع.']},
   {question:['Can family members be included?','هل يمكن ضم أفراد الأسرة؟'],answer:['A spouse or partner and eligible dependent children may be included, subject to definitions, documents, admissibility and fees.','يمكن ضم الزوج أو الشريك والأطفال المعالين المؤهلين وفق التعريفات والمستندات ومتطلبات القبول والرسوم.']}
  ]
 },
 'australia-skilled-migration':{
  overview:[
   ['Australia’s points-tested skilled program includes distinct visas with different status and nomination rules. Subclass 189 and 190 are permanent visas; subclass 491 is a provisional regional visa.','يشمل برنامج أستراليا للمهارات القائم على النقاط تأشيرات مختلفة في الوضع وشروط الترشيح. الفئتان 189 و190 دائمتان، بينما 491 تأشيرة إقليمية مؤقتة.'],
   ['An Expression of Interest in SkillSelect is not a visa application. Occupation eligibility, skills assessment, English, points and any nomination must be established before an invitation can lead to an application.','إبداء الاهتمام في SkillSelect ليس طلب تأشيرة. يجب إثبات أهلية المهنة وتقييم المهارات واللغة الإنجليزية والنقاط وأي ترشيح قبل أن تؤدي الدعوة إلى تقديم طلب.']
  ],
  pathways:[
   {name:['Subclass 189 · Skilled Independent','الفئة 189 · المهارات المستقلة'],status:['Permanent','دائمة'],description:['A points-tested permanent visa without state, territory or family sponsorship, subject to invitation.','تأشيرة دائمة قائمة على النقاط دون ترشيح ولاية أو إقليم أو كفالة أسرية، وتخضع للدعوة.']},
   {name:['Subclass 190 · Skilled Nominated','الفئة 190 · المهارات المرشحة'],status:['Permanent','دائمة'],description:['A points-tested permanent visa requiring nomination by an Australian state or territory.','تأشيرة دائمة قائمة على النقاط وتتطلب ترشيح ولاية أو إقليم أسترالي.']},
   {name:['Subclass 491 · Skilled Work Regional','الفئة 491 · العمل الماهر الإقليمي'],status:['Provisional regional','إقليمية مؤقتة'],description:['A provisional regional visa requiring qualifying nomination or family sponsorship, with a separate potential pathway to subclass 191 permanent residence after its conditions are met.','تأشيرة إقليمية مؤقتة تتطلب ترشيحاً مؤهلاً أو كفالة أسرية، ولها مسار محتمل منفصل إلى الإقامة الدائمة 191 بعد استيفاء شروطه.']}
  ],
  documents:[['Passport and civil-status records','جواز السفر ومستندات الحالة المدنية'],['Approved English-test evidence','إثبات اختبار اللغة الإنجليزية المعتمد'],['Positive skills assessment for the nominated occupation','تقييم مهارات إيجابي للمهنة المرشحة'],['Employment references and qualification records','خطابات الخبرة وسجلات المؤهلات'],['State or territory nomination evidence for subclass 190 or 491, where applicable','إثبات ترشيح الولاية أو الإقليم للفئة 190 أو 491 عند الانطباق'],['Health and character evidence when requested','أدلة الصحة والسيرة عند الطلب']],
  faqs:[
   {question:['Does 65 points guarantee an invitation?','هل تضمن 65 نقطة الدعوة؟'],answer:['No. Sixty-five is the current minimum points threshold for relevant points-tested visas, but invitation scores can be higher and depend on the occupation, route and invitation round.','لا. خمس وستون هي الحد الأدنى الحالي للتأشيرات المعنية القائمة على النقاط، لكن درجات الدعوة قد تكون أعلى بحسب المهنة والمسار وجولة الدعوات.']},
   {question:['Is subclass 491 permanent residence?','هل الفئة 491 إقامة دائمة؟'],answer:['No. It is a provisional regional visa. Eligible holders may later pursue subclass 191 if they meet its separate conditions.','لا. إنها تأشيرة إقليمية مؤقتة. وقد يتمكن حاملوها المؤهلون لاحقاً من التقدم للفئة 191 عند استيفاء شروطها المنفصلة.']},
   {question:['Do I need a skills assessment?','هل أحتاج إلى تقييم مهارات؟'],answer:['A suitable skills assessment is generally required for the nominated occupation before submitting the Expression of Interest. The assessing authority and evidence depend on the occupation.','يلزم عادةً تقييم مهارات مناسب للمهنة المرشحة قبل تقديم إبداء الاهتمام. تختلف جهة التقييم والأدلة بحسب المهنة.']},
   {question:['Can Plan B guarantee state nomination?','هل تستطيع بلان بي ضمان ترشيح الولاية؟'],answer:['No. States and territories set their own criteria and decide nominations. Plan B can help organise information and preparation only.','لا. تحدد الولايات والأقاليم معاييرها وتتخذ قرارات الترشيح. يقتصر دور بلان بي على تنظيم المعلومات والتحضير.']}
  ]
 },
 'australia-work-visas':{
  overview:[
   ['Employer-sponsored work routes are different from points-tested independent migration. The Skills in Demand visa (subclass 482) is temporary; the Employer Nomination Scheme (subclass 186) is permanent.','تختلف مسارات العمل برعاية صاحب العمل عن الهجرة المستقلة القائمة على النقاط. تأشيرة المهارات المطلوبة 482 مؤقتة، أما برنامج ترشيح صاحب العمل 186 فدائم.'],
   ['The role, sponsoring business, nominated occupation, market salary, skills, experience, English and any registration must be checked for the selected stream.','يجب التحقق من الوظيفة وصاحب العمل الراعي والمهنة المرشحة وراتب السوق والمهارات والخبرة واللغة الإنجليزية وأي ترخيص مطلوب للمسار المختار.']
  ],
  pathways:[
   {name:['Subclass 482 · Skills in Demand','الفئة 482 · المهارات المطلوبة'],status:['Temporary · generally 1–4 years','مؤقتة · عادةً من سنة إلى 4 سنوات'],description:['Employer-sponsored work in a nominated occupation. The official comparison currently states at least 12 months of relevant experience, with stream-specific salary and other rules.','عمل برعاية صاحب عمل في مهنة مرشحة. تشير المقارنة الرسمية حالياً إلى خبرة ذات صلة لا تقل عن 12 شهراً مع شروط راتب وغيرها بحسب المسار.']},
   {name:['Subclass 186 · Employer Nomination Scheme','الفئة 186 · برنامج ترشيح صاحب العمل'],status:['Permanent','دائمة'],description:['A permanent employer-nominated route with stream-specific skills assessment, employment, age, English and licensing rules.','مسار دائم بترشيح صاحب العمل وله متطلبات تقييم مهارات وتوظيف وعمر ولغة إنجليزية وترخيص تختلف بحسب المسار.']}
  ],
  documents:[['Passport and family civil-status documents','جواز السفر ومستندات الحالة المدنية للأسرة'],['Employer nomination and position details','تفاصيل ترشيح صاحب العمل والوظيفة'],['Employment references, qualifications and CV','خطابات الخبرة والمؤهلات والسيرة الذاتية'],['English-test results unless an exemption applies','نتائج اختبار الإنجليزية ما لم ينطبق إعفاء'],['Skills assessment or professional registration where required','تقييم المهارات أو التسجيل المهني عند الحاجة'],['Health and character evidence when requested','أدلة الصحة والسيرة عند الطلب']],
  faqs:[
   {question:['Did subclass 482 change?','هل تغيرت الفئة 482؟'],answer:['Yes. The Skills in Demand visa replaced the former Temporary Skill Shortage visa on 7 December 2024. Current stream and occupation rules should be checked at filing.','نعم. حلت تأشيرة المهارات المطلوبة محل تأشيرة نقص المهارات المؤقتة في 7 ديسمبر 2024. يجب مراجعة قواعد المسار والمهنة وقت التقديم.']},
   {question:['Does subclass 482 guarantee permanent residence?','هل تضمن الفئة 482 الإقامة الدائمة؟'],answer:['No. It is temporary. Some holders may later qualify for a permanent route such as subclass 186, but eligibility is separate and must be assessed at that time.','لا. إنها مؤقتة. قد يتأهل بعض حامليها لاحقاً لمسار دائم مثل 186، لكن الأهلية منفصلة ويجب تقييمها حينها.']},
   {question:['Can I change employers on a 482 visa?','هل يمكنني تغيير صاحب العمل على تأشيرة 482؟'],answer:['A new employer generally needs an approved nomination before you begin working for them. Visa conditions and transition periods must be checked for the individual case.','يحتاج صاحب العمل الجديد عادةً إلى ترشيح معتمد قبل بدء العمل لديه. يجب مراجعة شروط التأشيرة والفترات الانتقالية لكل حالة.']},
   {question:['Is a job placement guaranteed?','هل التوظيف مضمون؟'],answer:['No. This page does not advertise a vacancy or promise sponsorship. A genuine role and eligible sponsor must be confirmed independently.','لا. لا تعلن هذه الصفحة عن شاغر ولا تعد بالكفالة. يجب تأكيد وظيفة حقيقية وصاحب عمل مؤهل بشكل مستقل.']}
  ]
 },
 'germany-nursing':{
  overview:[
   ['Nursing is a regulated profession in Germany. Long-term work as a qualified nurse requires recognition of the foreign qualification and official permission to practise.','التمريض مهنة منظمة في ألمانيا. يتطلب العمل طويل الأجل كممرض مؤهل الاعتراف بالمؤهل الأجنبي والحصول على إذن رسمي لمزاولة المهنة.'],
   ['Depending on the recognition result, the route may involve full recognition, an adaptation period or a knowledge test. An employer offer and the appropriate employment or recognition residence route are separate parts of the plan.','بحسب نتيجة الاعتراف قد يشمل المسار اعترافاً كاملاً أو فترة تكيف أو اختبار معرفة. ويُعد عرض العمل ومسار الإقامة المناسب للعمل أو الاعتراف جزءين منفصلين من الخطة.']
  ],
  pathways:[
   {name:['Full recognition + qualified employment','اعتراف كامل + عمل مؤهل'],status:['Qualified-employment route','مسار عمل مؤهل'],description:['For a nurse whose qualification is fully recognised and who has the required professional permission and a qualifying job offer.','للممرض الذي تم الاعتراف الكامل بمؤهله وحصل على إذن الممارسة المطلوب وعرض عمل مستوفٍ.']},
   {name:['Recognition measure','إجراء استكمال الاعتراف'],status:['Recognition residence route','مسار إقامة للاعتراف'],description:['Where substantial differences are identified, an adaptation period or knowledge test may be required before full recognition.','عند وجود فروق جوهرية قد تُطلب فترة تكيف أو اختبار معرفة قبل الاعتراف الكامل.']},
   {name:['Recognition partnership','شراكة الاعتراف'],status:['Employer-linked recognition route','مسار اعتراف مرتبط بصاحب العمل'],description:['In suitable cases, a state-recognised foreign qualification, a qualifying employer agreement and at least A2 German can support recognition after entry; professional practice still requires the applicable higher standard.','في الحالات المناسبة قد يتيح مؤهل أجنبي معترف به رسمياً واتفاق مؤهل مع صاحب العمل ولغة ألمانية A2 استكمال الاعتراف بعد الدخول، مع بقاء معيار أعلى لمزاولة المهنة حسب الحالة.']}
  ],
  documents:[['Nursing diploma, transcript and detailed training syllabus','دبلوم التمريض وكشف الدرجات والمنهج التدريبي المفصل'],['Professional registration or licence and certificate of good standing','التسجيل أو الترخيص المهني وشهادة حسن السيرة المهنية'],['Employment records and detailed experience letters','سجلات العمل وخطابات الخبرة المفصلة'],['German-language certificate required for the selected stage','شهادة اللغة الألمانية المطلوبة للمرحلة المختارة'],['Recognition decision or correspondence from the competent authority','قرار الاعتراف أو مراسلات الجهة المختصة'],['Job offer, medical fitness and criminal-record evidence when required','عرض العمل وإثبات اللياقة الطبية والسجل الجنائي عند الحاجة']],
  faqs:[
   {question:['Is B2 German always required before entry?','هل يلزم B2 دائماً قبل الدخول؟'],answer:['B2 is generally required for full professional recognition. Some recognition or recognition-partnership routes can start with a lower level, but the state, employer and professional stage determine the exact requirement.','يلزم B2 عادةً للاعتراف المهني الكامل. قد تبدأ بعض مسارات الاعتراف أو شراكة الاعتراف بمستوى أدنى، لكن الولاية وصاحب العمل والمرحلة المهنية تحدد الشرط الدقيق.']},
   {question:['Is the salary fixed by the visa?','هل تحدد التأشيرة راتباً ثابتاً؟'],answer:['No. Pay, overtime, bonuses, leave and accommodation are employment terms. They must be checked in the real contract and against applicable German rules or collective agreements.','لا. الراتب والعمل الإضافي والمكافآت والإجازة والسكن شروط توظيف يجب مراجعتها في العقد الحقيقي ووفق القواعد أو الاتفاقيات الجماعية المطبقة في ألمانيا.']},
   {question:['What happens if my qualification is only partly recognised?','ماذا يحدث إذا كان الاعتراف بمؤهلي جزئياً؟'],answer:['The recognition decision may specify an adaptation period or knowledge test. The correct residence route and financing must then be planned around that measure.','قد يحدد قرار الاعتراف فترة تكيف أو اختبار معرفة. عندها يجب تخطيط مسار الإقامة والتمويل المناسبين لذلك الإجراء.']},
   {question:['Can family accompany me?','هل يمكن أن ترافقني الأسرة؟'],answer:['Family reunification may be possible, but it depends on the residence title, relationship, housing, livelihood and current consular requirements. It is not an employer benefit or automatic right on every route.','قد يكون لمّ الشمل ممكناً بحسب نوع الإقامة والعلاقة والسكن والقدرة المالية والمتطلبات القنصلية السارية. وهو ليس ميزة وظيفية ولا حقاً تلقائياً في كل مسار.']}
  ]
 },
 'germany-car-mechanics':{
  overview:[
   ['Automotive technicians may use a qualified-employment route where their vocational qualification and a concrete skilled job fit the immigration requirements. The exact German reference occupation and recognition position must be checked.','قد يستخدم فنيو السيارات مسار العمل المؤهل عندما يتوافق مؤهلهم المهني ووظيفتهم الماهرة المحددة مع متطلبات الهجرة. يجب تحديد المهنة الألمانية المرجعية وموقف الاعتراف بدقة.'],
   ['Car mechanic is not presented here as a guaranteed vacancy or a single national recruitment program. Employer criteria such as experience or language can be stricter than the visa minimum.','لا تُعرض مهنة ميكانيكي السيارات هنا كشاغر مضمون أو برنامج توظيف وطني واحد. قد تكون معايير صاحب العمل للخبرة أو اللغة أشد من الحد الأدنى للتأشيرة.']
  ],
  pathways:[
   {name:['Qualified professional employment','عمل مهني مؤهل'],status:['Employer-linked work route','مسار عمل مرتبط بصاحب العمل'],description:['A concrete qualified job and a recognised or comparable vocational qualification are central to the standard skilled-worker route.','تُعد الوظيفة المؤهلة المحددة والمؤهل المهني المعترف به أو القابل للمقارنة أساس مسار العامل الماهر المعتاد.']},
   {name:['Recognition partnership','شراكة الاعتراف'],status:['Recognition alongside employment','الاعتراف بالتوازي مع العمل'],description:['May allow the recognition procedure to continue after entry where the qualification, employer agreement, job and German-language conditions are met.','قد تسمح باستكمال إجراء الاعتراف بعد الدخول عند استيفاء شروط المؤهل واتفاق صاحب العمل والوظيفة واللغة الألمانية.']}
  ],
  documents:[['Vocational diploma, transcript and training-content evidence','الدبلوم المهني وكشف الدرجات وأدلة محتوى التدريب'],['Detailed employment references and CV','خطابات خبرة مفصلة وسيرة ذاتية'],['Recognition decision or qualification-comparability evidence where required','قرار الاعتراف أو دليل قابلية مقارنة المؤهل عند الحاجة'],['Concrete employment offer with duties and remuneration','عرض عمل محدد يوضح المهام والأجر'],['German-language evidence requested by the route or employer','إثبات اللغة الألمانية المطلوب للمسار أو صاحب العمل'],['Passport, insurance and civil-status records as requested','جواز السفر والتأمين ومستندات الحالة المدنية حسب الطلب']],
  faqs:[
   {question:['Is German A1 a universal visa requirement?','هل الألمانية A1 شرط عام للتأشيرة؟'],answer:['No. Language requirements depend on the residence route and employer. A recognition partnership currently requires at least A2, while another route or workplace may require a different level.','لا. تعتمد متطلبات اللغة على مسار الإقامة وصاحب العمل. تتطلب شراكة الاعتراف حالياً A2 على الأقل، وقد يتطلب مسار أو مكان عمل آخر مستوى مختلفاً.']},
   {question:['Is two years of experience mandatory for everyone?','هل سنتان من الخبرة إلزاميتان للجميع؟'],answer:['Not as a universal rule on this page. Experience is assessed against the occupation, immigration route, qualification and actual employer requirements.','ليس كقاعدة عامة في هذه الصفحة. تُقيّم الخبرة وفق المهنة ومسار الهجرة والمؤهل ومتطلبات صاحب العمل الفعلية.']},
   {question:['Are salary and accommodation guaranteed?','هل الراتب والسكن مضمونان؟'],answer:['No. Salary, overtime, leave, accommodation and transport are contract terms. They must be documented by a genuine employer and reviewed before commitment.','لا. الراتب والعمل الإضافي والإجازة والسكن والنقل شروط تعاقدية يجب أن يوثقها صاحب عمل حقيقي وتُراجع قبل الالتزام.']},
   {question:['Can Plan B find me a guaranteed job?','هل تستطيع بلان بي ضمان وظيفة لي؟'],answer:['No. Plan B can review preparation and coordinate agreed support, but does not advertise an unverified vacancy or guarantee employer selection.','لا. يمكن لبلان بي مراجعة التحضير وتنسيق الدعم المتفق عليه، لكنها لا تعلن شاغراً غير متحقق منه ولا تضمن اختيار صاحب العمل.']}
  ]
 },
 'sweden-work-permit':{
  overview:[
   ['This page covers Sweden’s standard employer-based work-permit route, not an open work permit. A signed employment agreement, compliant terms and employer participation are central.','تغطي هذه الصفحة مسار تصريح العمل السويدي المعتاد القائم على صاحب العمل، وليس تصريح عمل مفتوحاً. ويُعد اتفاق العمل الموقّع والشروط المستوفية ومشاركة صاحب العمل عناصر أساسية.'],
   ['From 1 June 2026, the general salary floor is 90% of the median salary current when the application is assessed, and pay must also match collective agreements or normal industry practice. Exceptions and transition rules require individual checking.','اعتباراً من 1 يونيو 2026 يبلغ الحد العام للراتب 90% من متوسط الراتب الساري عند تقييم الطلب، ويجب أيضاً أن يتوافق الأجر مع الاتفاقيات الجماعية أو الممارسة المعتادة في القطاع. تتطلب الاستثناءات والقواعد الانتقالية مراجعة فردية.']
  ],
  pathways:[
   {name:['Employee work permit','تصريح عمل للموظف'],status:['Employer-based temporary permission','إذن مؤقت قائم على صاحب العمل'],description:['The employer provides employment information and completes required recruitment and insurance steps; the applicant completes the permit application.','يقدم صاحب العمل معلومات التوظيف ويستكمل خطوات الإعلان والتأمين المطلوبة، ويستكمل المتقدم طلب التصريح.']},
   {name:['Accompanying family','الأسرة المرافقة'],status:['Separate residence applications','طلبات إقامة منفصلة'],description:['Eligible family may apply, but the worker must meet the applicable family maintenance rules. Adult family members and qualifying older children may work if permits are granted.','قد تتقدم الأسرة المؤهلة، مع وجوب استيفاء العامل لقواعد إعالة الأسرة المطبقة. ويمكن لأفراد الأسرة البالغين والأطفال الأكبر سناً المستوفين العمل إذا مُنحت التصاريح.']}
  ],
  documents:[['Valid passport and signed employment agreement','جواز سفر سارٍ واتفاق عمل موقّع'],['Employer’s role, salary and employment-condition information','معلومات صاحب العمل عن الوظيفة والراتب وشروط التوظيف'],['Evidence of required employer insurance','إثبات تأمينات صاحب العمل المطلوبة'],['Qualification or licence evidence where the occupation requires it','إثبات المؤهل أو الترخيص إذا كانت المهنة تتطلبه'],['Family relationship, housing and maintenance evidence for accompanying applications','إثباتات العلاقة والسكن والإعالة لطلبات الأسرة المرافقة']],
  faqs:[
   {question:['Is German A1 required for Sweden?','هل تُطلب الألمانية A1 للسويد؟'],answer:['No. German A1 is not a Swedish work-permit requirement. Any Swedish or English language requirement comes from the occupation, employer or licensing rules.','لا. الألمانية A1 ليست شرطاً لتصريح العمل السويدي. أي شرط للسويدية أو الإنجليزية مصدره المهنة أو صاحب العمل أو قواعد الترخيص.']},
   {question:['What salary is required?','ما الراتب المطلوب؟'],answer:['For decisions under the rules effective from 1 June 2026, salary generally must be at least 90% of the current Swedish median and also meet the occupation’s collective-agreement or customary level. The authority’s current figure must be checked when applying.','للقرارات الخاضعة للقواعد النافذة منذ 1 يونيو 2026 يجب أن يبلغ الراتب عادةً 90% على الأقل من متوسط الراتب السويدي الساري وأن يطابق مستوى الاتفاقية الجماعية أو العرف للمهنة. يجب مراجعة الرقم الحالي عند التقديم.']},
   {question:['Can I start work before approval?','هل يمكنني بدء العمل قبل الموافقة؟'],answer:['First-time applicants normally need the permit before travelling to begin work. Rules differ for people already lawfully in Sweden or changing employer, so the case must be checked.','يحتاج المتقدم لأول مرة عادةً إلى التصريح قبل السفر لبدء العمل. تختلف القواعد لمن يوجد قانونياً في السويد أو يغير صاحب العمل، لذا يجب فحص الحالة.']},
   {question:['Can my family work in Sweden?','هل تستطيع أسرتي العمل في السويد؟'],answer:['If accompanying family permits are granted, adult family members and children reaching the authority’s stated working age may work. Maintenance and health-insurance rules must be checked under the rules in force.','إذا مُنحت تصاريح الأسرة المرافقة، يمكن لأفراد الأسرة البالغين والأطفال الذين يبلغون سن العمل المحدد لدى الجهة العمل. ويجب مراجعة قواعد الإعالة والتأمين الصحي السارية.']}
  ]
 },
 'portugal-work-residence':{
  overview:[
   ['Portugal does not offer a blanket “open work permit” through this page. The correct route depends on whether the activity is employed, independent, highly qualified or temporary.','لا تقدم البرتغال عبر هذه الصفحة «تصريح عمل مفتوحاً» عاماً. يعتمد المسار الصحيح على كون النشاط عملاً لدى صاحب عمل أو مستقلاً أو عالي التأهيل أو مؤقتاً.'],
   ['For ordinary longer-term employed work, the planning path is generally a residence visa for subordinate work followed by the corresponding residence-permit formalities. Temporary work lasting less than a year has a separate temporary-stay visa route.','بالنسبة للعمل المعتاد لدى صاحب عمل لمدة أطول يكون المسار التخطيطي عادةً تأشيرة إقامة للعمل التابع ثم إجراءات تصريح الإقامة المقابلة. وللعمل المؤقت لأقل من سنة مسار تأشيرة إقامة مؤقتة منفصل.']
  ],
  pathways:[
   {name:['Employed work with residence visa','عمل لدى صاحب عمل بتأشيرة إقامة'],status:['Residence pathway','مسار إقامة'],description:['For qualifying longer-term subordinate employment, followed by the applicable AIMA residence process after arrival.','للعمل التابع المؤهل طويل الأجل، ويتبعه إجراء الإقامة المطبق لدى AIMA بعد الوصول.']},
   {name:['Temporary employed or independent work','عمل مؤقت تابع أو مستقل'],status:['Temporary stay · under one year','إقامة مؤقتة · أقل من سنة'],description:['A separate consular route exists for qualifying temporary professional activity lasting less than one year.','يوجد مسار قنصلي منفصل للنشاط المهني المؤقت المؤهل الذي تقل مدته عن سنة.']},
   {name:['Independent or other specialist activity','عمل مستقل أو نشاط تخصصي آخر'],status:['Route-specific','بحسب المسار'],description:['Independent, highly qualified and other categories use their own evidence and residence rules and should not be presented as one generic work permit.','للعمل المستقل والفئات عالية التأهيل وغيرها أدلتها وقواعد إقامتها الخاصة ولا ينبغي عرضها كتصريح عمل عام واحد.']}
  ],
  documents:[['Passport and proof of lawful residence in the consular jurisdiction','جواز السفر وإثبات الإقامة القانونية في نطاق القنصلية'],['Employment contract, promise of employment or qualifying service/business evidence','عقد العمل أو وعد العمل أو دليل الخدمة أو النشاط المؤهل'],['Accommodation and means-of-support evidence as required','إثبات السكن ووسائل الإعالة حسب المطلوب'],['Criminal-record certificate and insurance where requested','شهادة السجل الجنائي والتأمين عند الطلب'],['Qualification or professional-authorisation evidence for regulated work','إثبات المؤهل أو الترخيص المهني للعمل المنظم']],
  faqs:[
   {question:['Is this an open work permit?','هل هذا تصريح عمل مفتوح؟'],answer:['No. The correct visa and residence basis must match the employment, independent activity or other professional purpose.','لا. يجب أن يتوافق أساس التأشيرة والإقامة الصحيح مع العمل لدى صاحب عمل أو النشاط المستقل أو الغرض المهني الآخر.']},
   {question:['Do I need a job contract?','هل أحتاج إلى عقد عمل؟'],answer:['For the ordinary employed-work route, a contract or qualifying promise of employment is central. Other routes require different business, service or qualification evidence.','في مسار العمل المعتاد لدى صاحب عمل يُعد العقد أو وعد العمل المستوفي عنصراً أساسياً. وتتطلب المسارات الأخرى أدلة مختلفة للنشاط أو الخدمة أو المؤهل.']},
   {question:['Does a work residence permit guarantee citizenship after five years?','هل تضمن إقامة العمل الجنسية بعد خمس سنوات؟'],answer:['No. Residence and citizenship are different legal statuses. Naturalisation requires a separate application and all nationality-law conditions in force at that time.','لا. الإقامة والجنسية وضعان قانونيان مختلفان. يتطلب التجنس طلباً منفصلاً واستيفاء جميع شروط قانون الجنسية السارية حينها.']},
   {question:['Who decides the application?','من يقرر الطلب؟'],answer:['The competent Portuguese consular and immigration authorities decide. Plan B can help organise the route discussion and preparation but cannot promise approval or timing.','تقرر الجهات القنصلية والهجرة البرتغالية المختصة. يمكن لبلان بي المساعدة في مناقشة المسار وتنظيم التحضير لكنها لا تضمن الموافقة أو المدة.']}
  ]
 },
 'canada-c11':{
  overview:[
   ['C11 is a temporary work-permit category for a business owner whose proposed work can create or maintain significant economic, social or cultural benefit to Canada. It is not a fixed-price investment program or direct permanent-residence grant.','C11 فئة تصريح عمل مؤقت لصاحب عمل يمكن لعمله المقترح أن ينشئ أو يحافظ على منفعة اقتصادية أو اجتماعية أو ثقافية كبيرة لكندا. وهو ليس برنامج استثمار بسعر ثابت ولا منحة إقامة دائمة مباشرة.'],
   ['Current IRCC instructions require control of at least 51% of the business, sufficient business and personal support funds, a credible temporary plan and evidence of significant benefit.','تشترط تعليمات IRCC الحالية السيطرة على 51% على الأقل من النشاط وتوافر أموال كافية للنشاط ولإعالة المتقدم وخطة مؤقتة موثوقة وأدلة على المنفعة الكبيرة.']
  ],
  pathways:[
   {name:['Business-owner work permit · C11','تصريح عمل لصاحب نشاط · C11'],status:['Temporary · normally no more than 18 months','مؤقت · عادةً لا يتجاوز 18 شهراً'],description:['The owner actively establishes or operates the qualifying business. Extensions require a fresh assessment and are not automatic.','يؤسس المالك النشاط المؤهل أو يديره فعلياً. يتطلب التمديد تقييماً جديداً وليس تلقائياً.']},
   {name:['Possible later immigration planning','تخطيط هجرة لاحق محتمل'],status:['Separate assessment','تقييم منفصل'],description:['Any later permanent-residence option depends on a different program and the facts at that time. IRCC states C11 work experience does not count for Canadian Experience Class purposes.','يعتمد أي خيار لاحق للإقامة الدائمة على برنامج مختلف والوقائع حينها. وتذكر IRCC أن خبرة العمل عبر C11 لا تُحتسب لفئة الخبرة الكندية.']}
  ],
  documents:[['Ownership and corporate records showing at least 51% control','سجلات الملكية والشركة التي تثبت السيطرة على 51% على الأقل'],['Detailed viable business plan and implementation timetable','خطة عمل قابلة للتنفيذ وجدول تطبيق مفصل'],['Evidence of significant economic, social or cultural benefit','أدلة المنفعة الاقتصادية أو الاجتماعية أو الثقافية الكبيرة'],['Lawful business funds and separate personal support funds','أموال مشروعة للنشاط وأموال منفصلة للإعالة الشخصية'],['Management experience and active-operating plan','الخبرة الإدارية وخطة الإدارة الفعلية'],['Employer-compliance and work-permit evidence required for the filing','أدلة امتثال صاحب العمل وتصريح العمل المطلوبة للتقديم']],
  faqs:[
   {question:['Is CAD 200,000 a legal minimum?','هل 200 ألف دولار كندي حد قانوني أدنى؟'],answer:['IRCC’s C11 instructions do not set one blanket minimum investment. Capital must be credible and sufficient for the proposed business; any advisory budget must not be described as statutory eligibility.','لا تضع تعليمات C11 لدى IRCC حداً استثمارياً عاماً واحداً. يجب أن يكون رأس المال موثوقاً وكافياً للنشاط المقترح، ولا يجوز وصف أي ميزانية استشارية بأنها شرط قانوني.']},
   {question:['How much of the business must I own?','كم يجب أن أمتلك من النشاط؟'],answer:['Current IRCC instructions say the applicant should control at least 51% of the business for this business-owner category.','تنص تعليمات IRCC الحالية على أن يسيطر المتقدم على 51% على الأقل من النشاط ضمن فئة أصحاب الأعمال هذه.']},
   {question:['Is the permit valid for 18 months?','هل صلاحية التصريح 18 شهراً؟'],answer:['IRCC instructs officers that validity should not be longer than 18 months. The actual grant may be shorter and an extension requires a new decision.','توجه IRCC الموظفين إلى ألا تتجاوز الصلاحية 18 شهراً. قد تكون المنحة الفعلية أقصر، ويتطلب التمديد قراراً جديداً.']},
   {question:['Does C11 lead directly to permanent residence?','هل يؤدي C11 مباشرة إلى الإقامة الدائمة؟'],answer:['No. It is temporary. Any later permanent-residence strategy is separate, and C11 work experience does not count for Canadian Experience Class purposes under the current instructions.','لا. إنه مؤقت. أي استراتيجية لاحقة للإقامة الدائمة منفصلة، ولا تُحتسب خبرة C11 لفئة الخبرة الكندية وفق التعليمات الحالية.']}
  ]
 },
 'usa-eb5':{
  overview:[
   ['EB-5 is an immigrant investor classification. A qualifying investment in a new commercial enterprise must be at risk, lawfully sourced and connected to the required job creation.','EB-5 تصنيف للمستثمر المهاجر. يجب أن يكون الاستثمار المؤهل في مشروع تجاري جديد معرضاً للمخاطر ومشروع المصدر ومرتبطاً بإنشاء الوظائف المطلوبة.'],
   ['The current minimum is USD 1,050,000, or USD 800,000 for a qualifying targeted employment area or infrastructure investment. Project and immigration due diligence remain essential; government designation is not a guarantee.','الحد الأدنى الحالي هو 1,050,000 دولار أمريكي، أو 800,000 دولار لاستثمار مؤهل في منطقة توظيف مستهدفة أو مشروع بنية تحتية. تبقى العناية الواجبة للمشروع والهجرة ضرورية، ولا يشكل التصنيف الحكومي ضماناً.']
  ],
  pathways:[
   {name:['Standard EB-5 investment','استثمار EB-5 القياسي'],status:['USD 1,050,000 minimum','حد أدنى 1,050,000 دولار'],description:['Investment in a qualifying new commercial enterprise outside the reduced-investment categories.','استثمار في مشروع تجاري جديد مؤهل خارج فئات الاستثمار المخفض.']},
   {name:['TEA or infrastructure investment','استثمار منطقة توظيف مستهدفة أو بنية تحتية'],status:['USD 800,000 minimum','حد أدنى 800,000 دولار'],description:['Reduced threshold for a qualifying targeted employment area investment or qualifying infrastructure project under current law.','حد مخفض لاستثمار مؤهل في منطقة توظيف مستهدفة أو مشروع بنية تحتية مؤهل وفق القانون الحالي.']},
   {name:['Immigration outcome','النتيجة الهجرية'],status:['Conditional permanent residence','إقامة دائمة مشروطة'],description:['If the petition, visa or adjustment and admission are approved, the investor and eligible derivatives receive conditional residence and later petition to remove conditions.','إذا تمت الموافقة على العريضة والتأشيرة أو تعديل الوضع والدخول، يحصل المستثمر والمشتقون المؤهلون على إقامة مشروطة ثم يتقدمون لاحقاً لإزالة الشروط.']}
  ],
  documents:[['Passport and civil-status records for the investor and derivatives','جوازات السفر ومستندات الحالة المدنية للمستثمر والمرافقين'],['Complete lawful source-and-path-of-funds evidence','أدلة كاملة على المصدر والمسار المشروع للأموال'],['Investment subscription, transfer and escrow records','سجلات الاكتتاب والتحويل وحساب الضمان'],['Project offering and due-diligence materials','مستندات عرض المشروع والعناية الواجبة'],['Tax, business, property, gift or loan records supporting the capital source','السجلات الضريبية والتجارية والعقارية أو الهبات أو القروض الداعمة لمصدر رأس المال'],['Attorney-prepared petition and later conditional-residence evidence','العريضة التي يعدها المحامي وأدلة الإقامة المشروطة اللاحقة']],
  faqs:[
   {question:['What are the current EB-5 investment amounts?','ما مبالغ استثمار EB-5 الحالية؟'],answer:['For post-March 2022 filings, USCIS states USD 1,050,000 generally and USD 800,000 for a qualifying targeted employment area or infrastructure project. Additional fees and expenses are separate.','للطلبات بعد مارس 2022 تذكر USCIS مبلغ 1,050,000 دولار عموماً و800,000 دولار لمنطقة توظيف مستهدفة مؤهلة أو مشروع بنية تحتية. الرسوم والمصروفات الإضافية منفصلة.']},
   {question:['How many jobs must be created?','كم وظيفة يجب إنشاؤها؟'],answer:['The investment generally must create at least 10 qualifying full-time U.S. jobs, subject to the rules for the investment structure and filing.','يجب أن ينشئ الاستثمار عادةً 10 وظائف أمريكية مؤهلة بدوام كامل على الأقل، وفق قواعد هيكل الاستثمار والتقديم.']},
   {question:['Which family members may be included?','من أفراد الأسرة الذين يمكن ضمهم؟'],answer:['The investor’s spouse and eligible unmarried children under 21 may qualify as derivatives, subject to age-protection and individual eligibility rules.','قد يتأهل زوج المستثمر وأطفاله غير المتزوجين المؤهلون دون 21 عاماً كمرافقين، وفق قواعد حماية العمر والأهلية الفردية.']},
   {question:['Is the investment or Green Card guaranteed?','هل الاستثمار أو البطاقة الخضراء مضمونان؟'],answer:['No. Capital is at risk; project performance, repayment, job creation, petition approval and visa availability are not guaranteed. Independent U.S. legal, financial and investment advice is essential.','لا. رأس المال معرض للمخاطر، ولا تُضمن نتائج المشروع أو السداد أو إنشاء الوظائف أو قبول العريضة أو توافر التأشيرة. المشورة القانونية والمالية والاستثمارية الأمريكية المستقلة ضرورية.']},
   {question:['How is EB-5 different from E-2?','كيف يختلف EB-5 عن E-2؟'],answer:['EB-5 is an immigrant route leading first to conditional permanent residence if approved. E-2 is temporary treaty-investor status and does not itself provide a direct Green Card route.','EB-5 مسار مهاجر يؤدي أولاً إلى إقامة دائمة مشروطة عند الموافقة. أما E-2 فهو وضع مؤقت لمستثمر المعاهدة ولا يمنح بحد ذاته مساراً مباشراً للبطاقة الخضراء.']}
  ]
 },
 'usa-e2':{
  overview:[
   ['E-2 is a temporary, nonimmigrant classification for eligible nationals of treaty countries who invest substantially in and develop and direct a real operating U.S. enterprise.','E-2 تصنيف مؤقت لغير المهاجرين لمواطني دول المعاهدة المؤهلين الذين يستثمرون مبلغاً جوهرياً في نشاط أمريكي تشغيلي حقيقي ويطورونه ويديرونه.'],
   ['There is no single statutory minimum investment. The amount must be substantial relative to the business, committed and at risk, and sufficient to support successful operation rather than a marginal enterprise.','لا يوجد حد استثمار قانوني واحد. يجب أن يكون المبلغ جوهرياً نسبةً إلى النشاط وملتزماً ومعرضاً للمخاطر وكافياً لدعم التشغيل الناجح لا نشاطاً هامشياً.']
  ],
  pathways:[
   {name:['Principal treaty investor','المستثمر الرئيسي من دولة معاهدة'],status:['Temporary nonimmigrant status','وضع مؤقت لغير المهاجرين'],description:['The investor develops and directs an enterprise with treaty-country nationality, generally through at least 50% ownership or other operational control.','يطور المستثمر ويدير نشاطاً يحمل جنسية دولة المعاهدة، عادةً عبر ملكية 50% على الأقل أو سيطرة تشغيلية أخرى.']},
   {name:['Treaty-enterprise employee','موظف منشأة المعاهدة'],status:['Executive, supervisory or essential skills','تنفيذي أو إشرافي أو مهارات أساسية'],description:['Certain employees sharing the enterprise’s treaty nationality may qualify in an executive, supervisory or essential-skills role.','قد يتأهل بعض الموظفين الذين يحملون جنسية المعاهدة نفسها للمنشأة في دور تنفيذي أو إشرافي أو ذي مهارات أساسية.']},
   {name:['Immigration outcome','النتيجة الهجرية'],status:['No direct permanent residence','لا إقامة دائمة مباشرة'],description:['E-2 can be renewed when requirements continue to be met, but it is not EB-5 and does not itself convert into a Green Card.','يمكن تجديد E-2 عند استمرار استيفاء الشروط، لكنه ليس EB-5 ولا يتحول بحد ذاته إلى بطاقة خضراء.']}
  ],
  documents:[['Treaty-country passport and nationality evidence','جواز دولة المعاهدة وإثبات الجنسية'],['Enterprise ownership and treaty-nationality records','سجلات ملكية المنشأة وجنسيتها وفق المعاهدة'],['Lawful source and path of investment funds','المصدر والمسار المشروع لأموال الاستثمار'],['Evidence that funds are committed and at risk','إثبات التزام الأموال وتعريضها للمخاطر'],['Operating business records, premises, licences and contracts','سجلات تشغيل النشاط والمقر والتراخيص والعقود'],['Business plan, staffing projections and evidence of control','خطة العمل وتوقعات التوظيف وأدلة السيطرة']],
  faqs:[
   {question:['Is residence in Kuwait enough for E-2 eligibility?','هل تكفي الإقامة في الكويت لأهلية E-2؟'],answer:['No. Eligibility depends on nationality of a treaty country, not residence in Kuwait. The current treaty-country and reciprocity schedules must be checked.','لا. تعتمد الأهلية على جنسية دولة معاهدة وليس الإقامة في الكويت. يجب مراجعة قوائم دول المعاهدة والمعاملة بالمثل الحالية.']},
   {question:['Is there a fixed minimum investment?','هل يوجد حد استثمار أدنى ثابت؟'],answer:['No single dollar minimum applies to every E-2 case. The proportionality, commitment, risk and operating needs of the specific business are examined.','لا ينطبق حد دولاري واحد على كل حالات E-2. تُفحص نسبة الاستثمار والتزامه ومخاطره واحتياجات تشغيل النشاط المحدد.']},
   {question:['Can my family accompany me?','هل يمكن أن ترافقني أسرتي؟'],answer:['A spouse and unmarried children under 21 may apply to accompany or join the investor. Work and study consequences should be reviewed individually under current rules.','يمكن للزوج والأطفال غير المتزوجين دون 21 عاماً التقدم للمرافقة أو الالتحاق بالمستثمر. يجب مراجعة آثار العمل والدراسة لكل فرد وفق القواعد الحالية.']},
   {question:['Does E-2 lead directly to a Green Card?','هل يؤدي E-2 مباشرة إلى البطاقة الخضراء؟'],answer:['No. E-2 is temporary nonimmigrant status. Any permanent-residence strategy is separate and requires its own legal basis.','لا. E-2 وضع مؤقت لغير المهاجرين. أي استراتيجية للإقامة الدائمة منفصلة وتتطلب أساساً قانونياً خاصاً بها.']},
   {question:['How is E-2 different from EB-5?','كيف يختلف E-2 عن EB-5؟'],answer:['E-2 depends on treaty nationality and a substantial active investment but is temporary. EB-5 has statutory investment and job-creation thresholds and is an immigrant route to conditional permanent residence.','يعتمد E-2 على جنسية دولة المعاهدة واستثمار نشط جوهري لكنه مؤقت. أما EB-5 فله حدود قانونية للاستثمار وإنشاء الوظائف وهو مسار مهاجر إلى إقامة دائمة مشروطة.']}
  ]
 }
};
