/**
 * Hand-written search titles and meta descriptions for programme pages (English + Arabic).
 * Each page owns one primary intent (see SEO-LEADGEN-REPORT.md); wording follows the visible page content and
 * CONTENT-REVIEW.md: no promised approvals, salaries, timelines or vacancies. Titles omit the " | Plan B Consultant" suffix added in lib/seo.ts.
 */
export const programmeMeta:Record<string,{title:[string,string];description:[string,string]}>={
 'canada-express-entry':{title:['Canada Express Entry from Kuwait','الهجرة إلى كندا عبر الدخول السريع من الكويت'],description:['Understand Express Entry, Federal Skilled Worker points versus CRS, documents and process, then request a free initial assessment from Plan B in Kuwait.','تعرّف على الدخول السريع الكندي ونقاط العمال المهرة مقابل CRS والمستندات والخطوات، ثم اطلب تقييماً أولياً مجانياً من بلان بي في الكويت.']},
 'australia-skilled-migration':{title:['Australia skilled migration: 189, 190, 491','الهجرة المهارية إلى أستراليا: 189 و190 و491'],description:['Compare the Australian skilled visa subclasses 189, 190 and 491, see why occupation and nomination matter, and request a free initial assessment.','قارن بين فئات التأشيرة المهارية الأسترالية 189 و190 و491 وأثر المهنة والترشيح، ثم اطلب تقييماً أولياً مجانياً.']},
 'australia-work-visas':{title:['Australia employer-sponsored work visas','تأشيرات العمل في أستراليا برعاية صاحب العمل'],description:['Learn how the Skills in Demand 482 visa and Employer Nomination Scheme 186 work, what sponsorship involves, and request a free initial assessment.','تعرّف على تأشيرة المهارات المطلوبة 482 ونظام ترشيح صاحب العمل 186 وما تتطلبه الرعاية، ثم اطلب تقييماً أولياً مجانياً.']},
 'germany-nursing':{title:['Nursing in Germany: recognition and language','التمريض في ألمانيا: الاعتراف المهني واللغة'],description:['Plan a nursing career in Germany: professional recognition, German-language preparation and job offers. Request a free initial assessment from Kuwait.','خطط لمسار التمريض في ألمانيا: الاعتراف المهني والاستعداد للغة الألمانية وعروض العمل، ثم اطلب تقييماً أولياً مجانياً من الكويت.']},
 'germany-car-mechanics':{title:['Car mechanic careers in Germany','العمل كميكانيكي سيارات في ألمانيا'],description:['Explore skilled automotive work in Germany: qualification recognition, a verified job offer and the documents to prepare. Free initial assessment.','استكشف العمل الماهر في قطاع السيارات بألمانيا: الاعتراف بالمؤهل وعرض العمل الموثّق والمستندات المطلوبة، مع تقييم أولي مجاني.']},
 'sweden-work-permit':{title:['Sweden work permit requirements','شروط تصريح العمل في السويد'],description:['How an employer-based Swedish work permit works: job offer, salary and insurance conditions, documents and process. Request a free initial assessment.','كيف يعمل تصريح العمل السويدي المرتبط بصاحب العمل: عرض الوظيفة والراتب والتأمين والمستندات والخطوات، مع تقييم أولي مجاني.']},
 'portugal-work-residence':{title:['Portugal work visa and residence routes','تأشيرة العمل والإقامة في البرتغال'],description:['Identify the right Portuguese work visa or residence category before applying, and see the documents and steps involved. Free initial assessment.','حدّد فئة التأشيرة أو الإقامة البرتغالية المناسبة قبل التقديم، وتعرّف على المستندات والخطوات، مع تقييم أولي مجاني.']},
 'canada-c11':{title:['Canada C11 business owner work permit','تصريح عمل كندا C11 لأصحاب الأعمال'],description:['Understand Canada’s LMIA-exempt C11 work permit for business owners: the significant-benefit test, documents and limits. Free initial assessment.','تعرّف على تصريح العمل الكندي C11 المعفى من تقييم أثر سوق العمل: اختبار المنفعة المهمة والمستندات والحدود، مع تقييم أولي مجاني.']},
 'usa-eb5':{title:['USA EB-5 immigrant investor route','مسار المستثمر المهاجر الأمريكي EB-5'],description:['How the EB-5 immigrant investor route to U.S. permanent residence works, what it requires and where legal advice is needed. Free initial assessment.','كيف يعمل مسار EB-5 للإقامة الدائمة الأمريكية عبر الاستثمار وما يتطلبه ومتى تلزم المشورة القانونية، مع تقييم أولي مجاني.']},
 'usa-e2':{title:['USA E-2 treaty investor visa','تأشيرة المستثمر الأمريكية E-2'],description:['E-2 is temporary treaty-investor status, not a green card. See the eligibility points, documents and process, then request a free initial assessment.','E-2 وضع مؤقت للمستثمر بموجب معاهدة وليس إقامة دائمة. تعرّف على الأهلية والمستندات والخطوات، ثم اطلب تقييماً أولياً مجانياً.']},
 'citizenship-investment':{title:['Citizenship by investment overview','نظرة عامة على الجنسية عن طريق الاستثمار'],description:['Compare your mobility, family and investment objectives before considering a specific citizenship programme.','قارن بين أهداف التنقل والأسرة والاستثمار قبل دراسة برنامج جنسية محدد، واطلب استفساراً أولياً من بلان بي في الكويت.']},
 'study-visas':{title:['Study abroad and student visa support','الدراسة بالخارج وتأشيرات الطلاب'],description:['Prepare for a student visa: admission status, documents and process. Request a free initial assessment from Plan B Consultant in Kuwait.','استعد لتأشيرة الطالب: حالة القبول والمستندات والخطوات، ثم اطلب تقييماً أولياً مجانياً من بلان بي في الكويت.']},
 'visit-visas':{title:['Visit visa support for tourism and family','المساعدة في تأشيرات الزيارة والسياحة'],description:['Prepare a clear visit-visa application for tourism, family visits or permitted short business trips. Request a free initial assessment from Kuwait.','جهّز طلب تأشيرة زيارة واضحاً للسياحة أو زيارة الأسرة أو رحلات الأعمال القصيرة المسموح بها، واطلب تقييماً أولياً مجانياً.']}
};

/** Service-overview titles and descriptions (scope of assistance, distinct from the programme pages that explain specific routes). */
export const serviceMeta:Record<string,{title:[string,string];description:[string,string]}>={
 'residency-by-investment':{title:['Residency through investment guidance','إرشاد الإقامة عن طريق الاستثمار'],description:['Explore whether an investment-related residence route fits your family plans, starting with the documented U.S. EB-5 programme. Initial enquiry is free.','استكشف مدى ملاءمة مسار إقامة مرتبط بالاستثمار لخطط أسرتك، بدءاً ببرنامج EB-5 الأمريكي الموضح. الاستفسار الأولي مجاني.']},
 'citizenship-by-investment':{title:['Citizenship by investment: first enquiry','الجنسية عن طريق الاستثمار: استفسار أولي'],description:['Discuss your citizenship and mobility goals before choosing a programme. This overview is an enquiry service and offers no specific country or package.','ناقش أهداف الجنسية والتنقل قبل اختيار البرنامج. هذه الصفحة خدمة استفسار أولي ولا تعرض دولة محددة أو حزمة استثمارية.']},
 'skilled-immigration':{title:['Skilled immigration assistance from Kuwait','المساعدة في هجرة الكفاءات من الكويت'],description:['Explore skilled migration pathways around your qualifications and experience: destination discussion, profile review, preparation guidance and family relocation.','استكشف مسارات هجرة الكفاءات وفق مؤهلاتك وخبراتك: مناقشة الوجهة ومراجعة الملف وإرشاد التحضير واعتبارات انتقال الأسرة.']},
 'work-visas':{title:['Work visa and permit assistance','المساعدة في تأشيرات وتصاريح العمل'],description:['Understand the preparation steps for working abroad: offer status review, destination-specific document guidance and application preparation support.','تعرّف على خطوات التحضير للعمل في الخارج: مراجعة حالة العرض الوظيفي وإرشاد المستندات حسب الوجهة ودعم تجهيز الطلب.']},
 'visit-visas':{title:['Visit visa assistance from Kuwait','المساعدة في تأشيرات الزيارة من الكويت'],description:['Prepare for a holiday or family visit with a travel-purpose discussion, document checklist guidance and help preparing your application.','استعد لإجازتك أو زيارة عائلتك بمناقشة غرض السفر وإرشاد قائمة المستندات والمساعدة في تجهيز الطلب.']},
 'study-abroad':{title:['Student visa assistance from Kuwait','المساعدة في تأشيرات الدراسة من الكويت'],description:['Discuss study plans, admission status and student-visa preparation. Scope, responsibilities and next steps are explained before you commit.','ناقش خطط الدراسة وحالة القبول والتحضير لتأشيرة الطالب. يُوضح النطاق والمسؤوليات والخطوات التالية قبل أي التزام.']},
 'global-job-search':{title:['Global job search support: CVs and LinkedIn','دعم البحث عن عمل عالمي: السيرة ولينكدإن'],description:['Career planning, professional CVs, cover letters and LinkedIn profiles for an international job search. A job search does not itself grant work permission.','تخطيط مهني وسير ذاتية احترافية وخطابات تغطية وملفات لينكدإن للبحث عن عمل دولي. البحث عن وظيفة لا يمنح بحد ذاته تصريح عمل.']},
 'business-immigration':{title:['Business immigration assistance','الاستشارة في هجرة الأعمال'],description:['Explore international business and residency options around your entrepreneurial goals: destination review, requirements overview and agreed application support.','استكشف خيارات الأعمال والإقامة الدولية وفق أهدافك الريادية: مراجعة الوجهات ونظرة على المتطلبات ودعم الطلب المتفق عليه.']},
 'family-visas':{title:['Family and dependent visa assistance','المساعدة في تأشيرات الأسرة والمعالين'],description:['Understand how to join or accompany family abroad: relationship document preparation, destination-specific checklists and application preparation.','تعرّف على خطوات الانضمام إلى عائلتك أو مرافقتها في الخارج: تجهيز مستندات القرابة وقوائم المستندات حسب الوجهة وتجهيز الطلب.']},
 'permanent-residency':{title:['Permanent residency application support','دعم طلبات الإقامة الدائمة'],description:['Discuss residency applications, document guidance and PR-card renewal preparation where applicable, with clear next steps.','ناقش طلبات الإقامة وإرشاد المستندات والتحضير لتجديد بطاقة الإقامة الدائمة عند انطباقه، مع خطوات تالية واضحة.']},
 'ielts-preparation':{title:['IELTS preparation for study, work or migration','الاستعداد لاختبار آيلتس للدراسة والعمل والهجرة'],description:['Plan IELTS preparation around your education, career or migration goals, with guidance on listening, reading, writing and speaking practice.','خطط للاستعداد لاختبار آيلتس وفق أهدافك الدراسية أو المهنية أو للهجرة، مع إرشاد للتدريب على الاستماع والقراءة والكتابة والمحادثة.']},
 'settlement-support':{title:['Pre-departure and settlement support','الدعم قبل السفر وبعد الاستقرار'],description:['Organise practical questions before you leave and discuss agreed support after arrival: checklists, arrival planning and local-system information.','نظّم أسئلتك العملية قبل السفر وناقش الدعم المتفق عليه بعد الوصول: قوائم التحضير وتخطيط الوصول ومعلومات عن الأنظمة المحلية.']}
};
