import type {Metadata} from 'next';
import {services,countries,guides,slugify,origin,business,type Locale} from './content';
import {programmes} from './programmes';
import {programmeMeta,serviceMeta} from './seo-copy';
export const routePaths=[...new Set(['','about','programmes','services','destinations','resources','consultation','contact','privacy','faqs',...programmes.map(p=>'programmes/'+p.slug),...services.map(s=>'services/'+s.slug),...countries.map(c=>'destinations/'+slugify(c[0])),...guides.map(g=>'resources/'+g.slug)])];
/** Bump together with VERSION in scripts/prepare-social-images.mjs whenever the sharing image changes, so WhatsApp/Facebook fetch a new URL. */
export const shareVersion='v3';
export const supportedCountries=['canada','australia','germany','sweden','portugal','united-states'];
export const indexingEnabled=process.env.NEXT_PUBLIC_ALLOW_INDEXING==='true'&&process.env.VERCEL_ENV!=='preview';
export function eligiblePath(path:string){return !(path.startsWith('destinations/')&&!supportedCountries.includes(path.split('/')[1]))&&path!=='programmes/citizenship-investment';}
export const indexablePaths=routePaths.filter(eligiblePath);
const sections:Record<string,[string,string,string,string]>={
 '':['Immigration consultancy in Kuwait','استشارات الهجرة في الكويت','Plan B Consultant helps individuals, families and businesses in Kuwait explore immigration, overseas work, study, visit and investment pathways.','تساعدك بلان بي كونسلتنت في الكويت على فهم خيارات الهجرة والعمل والدراسة والزيارة والاستثمار في الخارج والتحضير لخطوتك القادمة.'],
 about:['About our Kuwait immigration consultancy','عن بلان بي للاستشارات في الكويت','Meet Plan B Consultant’s approach to global mobility: a review of your goals, clear preparation steps and defined responsibilities from Kuwait.','تعرّف على نهج بلان بي كونسلتنت في الكويت: فهم أهدافك وتوضيح خطوات التحضير والمسؤوليات لخطط الانتقال إلى الخارج.'],
 programmes:['Immigration, work and investment programmes','برامج الهجرة والعمل والاستثمار','Compare the immigration, work, study, visit and business routes explained by Plan B Consultant, with eligibility and status distinctions.','استكشف برامج بلان بي للهجرة والعمل والدراسة والزيارة والأعمال، وتعرّف على شروط كل مسار ونوع الإقامة التي قد يوفرها.'],
 services:['Visa and global mobility assistance from Kuwait','خدمات التأشيرات والانتقال من الكويت','Find support for visa preparation, skilled immigration, family applications, job search, language preparation and settlement planning.','استكشف خدمات إعداد طلبات التأشيرة وهجرة الكفاءات ولمّ الشمل والبحث عن عمل والتحضير اللغوي والتخطيط للاستقرار.'],
 destinations:['Compare overseas destinations and pathways','اختيار وجهة الهجرة والعمل بالخارج','Explore destination overviews and follow the documented Canada, Australia, Germany, Sweden, Portugal and United States programmes.','استعرض الوجهات وتابع البرامج الموضحة لكندا وأستراليا وألمانيا والسويد والبرتغال والولايات المتحدة بحسب هدفك.'],
 resources:['Immigration consultation and document guides','أدلة الاستشارة وتجهيز المستندات','Read practical guides to preparing for a consultation, separating job search from work permission and organising documents securely.','اقرأ إرشادات عملية للاستعداد للاستشارة والتمييز بين البحث عن وظيفة وتصريح العمل وتنظيم المستندات ومشاركتها بأمان.'],
 consultation:['Request an immigration consultation from Kuwait','طلب استشارة هجرة من الكويت','Share your plans with Plan B Consultant for an initial review. Understand the next steps; an enquiry does not confirm eligibility or an appointment.','شارك خططك مع بلان بي للمراجعة الأولية وتوضيح الخطوات التالية. الاستفسار لا يعني تأكيد الأهلية أو حجز موعد.'],
 contact:['Contact Plan B Consultant in Kuwait','التواصل مع بلان بي كونسلتنت في الكويت','Contact our Kuwait-based team by phone, email or WhatsApp to discuss your immigration, work, study or investment enquiry.','تواصل مع فريق بلان بي في الكويت عبر الهاتف أو البريد الإلكتروني أو واتساب لمناقشة استفسارك حول الهجرة أو العمل أو الدراسة أو الاستثمار.'],
 privacy:['Enquiry privacy and personal information','خصوصية الاستفسارات والبيانات الشخصية','Understand the information requested by Plan B Consultant’s enquiry forms, its purpose and precautions when sharing personal documents.','تعرّف على البيانات المطلوبة في نماذج بلان بي والغرض منها واحتياطات مشاركة المستندات الشخصية.'],
 faqs:['Immigration and visa consultation questions','أسئلة حول استشارات الهجرة والتأشيرات','Answers about Plan B Consultant’s initial assessments, service scope, visa decisions and preparing for your first conversation.','إجابات حول التقييم الأولي ونطاق خدمات بلان بي وقرارات التأشيرة والاستعداد للمحادثة الأولى.']};
export function pageCopy(locale:Locale,path:string){
 const ar=locale==='ar',parts=path.split('/');
 const p=parts[0]==='programmes'?programmes.find(p=>p.slug===parts[1]):undefined,s=parts[0]==='services'?services.find(s=>s.slug===parts[1]):undefined,c=parts[0]==='destinations'?countries.find(c=>slugify(c[0])===parts[1]):undefined,g=parts[0]==='resources'?guides.find(g=>g.slug===parts[1]):undefined;
 if(p){const m=programmeMeta[p.slug];return m?{title:m.title[ar?1:0],description:m.description[ar?1:0],label:ar?p.ar:p.title}:{title:ar?`${p.ar} — إرشاد من الكويت`:`${p.title} guidance from Kuwait`,description:ar?p.introAr:p.intro,label:ar?p.ar:p.title}}
 if(s){const m=serviceMeta[s.slug];return {title:m?m.title[ar?1:0]:ar?`${s.ar} — خدمات بلان بي`:`${s.title} assistance`,description:m?m.description[ar?1:0]:ar?s.descriptionAr:s.description,label:ar?s.ar:s.title}}
 if(c)return {title:ar?`${c[1]}: نظرة على خيارات السفر والانتقال`:`${c[0]}: destination and mobility overview`,description:ar?`تعرّف على ${c[1]} كوجهة محتملة، وميّز بين الزيارة والدراسة والعمل والإقامة قبل مناقشة خطتك مع بلان بي.`:`Consider ${c[0]} as a destination, distinguish visits, study, work and residence, and discuss your plans with Plan B Consultant.`,label:c[ar?1:0]};
 if(g)return {title:g[ar?'ar':'title'],description:g[ar?'introAr':'intro'],label:g[ar?'ar':'title']};
 const entry=sections[path]||sections[''];return {title:entry[ar?1:0],description:entry[ar?3:2],label:entry[ar?1:0]};
}
export function pageMetadata(locale:Locale,path:string):Metadata{
 const copy=pageCopy(locale,path),url=origin+'/'+locale+(path?'/'+path:'');
 const image={url:`${origin}/images/social/plan-b-share-${shareVersion}-${locale}.jpg`,width:1200,height:630,type:'image/jpeg',alt:locale==='ar'?'بلان بي كونسلتنت — حلول عالمية استراتيجية من الكويت':'Plan B Consultant — Strategic Global Solutions from Kuwait'};
 return {title:copy.title+' | Plan B Consultant',description:copy.description,alternates:{canonical:url,languages:{en:origin+'/en'+(path?'/'+path:''),ar:origin+'/ar'+(path?'/'+path:'')}},robots:{index:indexingEnabled&&eligiblePath(path),follow:true},openGraph:{type:'website',url,title:copy.title+' | Plan B Consultant',description:copy.description,siteName:'Plan B Consultant',locale:locale==='ar'?'ar_AR':'en_GB',alternateLocale:locale==='ar'?'en_GB':'ar_AR',images:[image]},twitter:{card:'summary_large_image',title:copy.title+' | Plan B Consultant',description:copy.description,images:[{url:image.url,alt:image.alt}]}};
}
function httpsUrl(value?:string){try{const u=new URL(value||'');return u.protocol==='https:'?u.href:undefined}catch{return undefined}}
export function entityGraph(locale:Locale,path:string){
 const url=origin+'/'+locale+(path?'/'+path:''),copy=pageCopy(locale,path),organization=origin+'/#organization',website=origin+'/#website';
 const sameAs=[process.env.NEXT_PUBLIC_LINKEDIN_URL,process.env.NEXT_PUBLIC_FACEBOOK_URL,process.env.NEXT_PUBLIC_INSTAGRAM_URL,process.env.NEXT_PUBLIC_TIKTOK_URL||'https://www.tiktok.com/@planbconsultant'].map(httpsUrl).filter(Boolean);
 const graph:Record<string,unknown>[]=[{'@type':'Organization','@id':organization,name:'Plan B Consultant',url:origin,logo:{'@type':'ImageObject',url:origin+'/images/plan-b-crest-512.png',width:512,height:512},areaServed:{'@type':'Country',name:'Kuwait'},telephone:business.phone,email:business.email,...(sameAs.length?{sameAs}:{})},{'@type':'WebSite','@id':website,url:origin,name:'Plan B Consultant',publisher:{'@id':organization},inLanguage:['en','ar']},{'@type':'WebPage','@id':url+'#page',url,name:copy.title,description:copy.description,inLanguage:locale,isPartOf:{'@id':website},breadcrumb:{'@id':url+'#breadcrumb'}},{'@type':'BreadcrumbList','@id':url+'#breadcrumb',itemListElement:[{'@type':'ListItem',position:1,name:locale==='ar'?'الرئيسية':'Home',item:origin+'/'+locale},...(path?path.split('/').map((_,i,parts)=>{const p=parts.slice(0,i+1).join('/');return {'@type':'ListItem',position:i+2,name:pageCopy(locale,p).label,item:origin+'/'+locale+'/'+p}}):[])]}];
 if(path.startsWith('programmes/')||path.startsWith('services/'))graph.push({'@type':'Service','@id':url+'#service',name:copy.label,description:copy.description,url,provider:{'@id':organization},areaServed:{'@type':'Country',name:'Kuwait'}});
 if(path.startsWith('resources/'))graph.push({'@type':'Article','@id':url+'#article',headline:copy.title,description:copy.description,inLanguage:locale,mainEntityOfPage:{'@id':url+'#page'},publisher:{'@id':organization}});
 return {'@context':'https://schema.org','@graph':graph};
}
